export const DTC_DESCRIPTIONS: Record<string, string> = {
  P0001: 'Yakıt Hacim Regülatör Kontrol Devresi / Açık',
  P0010: 'Eksantrik Mili Konum Aktüatör Devresi / Açık (Banka 1)',
  P0011: 'Eksantrik Mili Konum Zamanlaması Çok İleri (Banka 1)',
  P0012: 'Eksantrik Mili Konum Zamanlaması Çok Geri (Banka 1)',
  P0013: 'Eksantrik Mili Konum Aktüatör Devresi / Açık (Banka 2)',
  P0014: 'Eksantrik Mili Konum Zamanlaması Çok İleri (Banka 2)',
  P0015: 'Eksantrik Mili Konum Zamanlaması Çok Geri (Banka 2)',
  P0016: 'Krank Mili - Eksantrik Mili Konum Sensörü Uyumsuzluğu (Banka 1)',
  P0017: 'Krank Mili - Eksantrik Mili Konum Sensörü Uyumsuzluğu (Banka 2)',
  P0020: 'Eksantrik Mili Konum Aktüatör Devresi (Sıra 2)',
  P0021: 'Eksantrik Mili Zamanlaması Çok İleri (Banka 2)',
  P0022: 'Eksantrik Mili Zamanlaması Çok Geri (Banka 2)',
  P0030: 'HO2S Isıtıcı Kontrol Devresi (Banka 1, Sensör 1)',
  P0031: 'HO2S Isıtıcı Kontrol Devresi Düşük (Banka 1, Sensör 1)',
  P0032: 'HO2S Isıtıcı Kontrol Devresi Yüksek (Banka 1, Sensör 1)',
  P0033: 'Turbo Şarj Atık Kapısı Kontrol Devresi',
  P0034: 'Turbo Şarj Atık Kapısı Kontrol Devresi Düşük',
  P0035: 'Turbo Şarj Atık Kapısı Kontrol Devresi Yüksek',
  P0040: 'O2 Sensörü Sinyal Değişimi (Banka 1, Sensör 1 ve 2)',
  P0041: 'O2 Sensörü Sinyal Değişimi (Banka 2, Sensör 1 ve 2)',
  P0050: 'HO2S Isıtıcı Kontrol Devresi (Banka 2, Sensör 1)',
  P0051: 'HO2S Isıtıcı Kontrol Devresi Düşük (Banka 2, Sensör 1)',
  P0052: 'HO2S Isıtıcı Kontrol Devresi Yüksek (Banka 2, Sensör 1)',
  P0068: 'MAP/MAF - Gaz Kelebeği Pozisyonu Uyumsuzluğu',
  P0070: 'Ortam Hava Sıcaklığı Sensörü Devresi',
  P0071: 'Ortam Hava Sıcaklığı Sensörü Aralık/Performans',
  P0072: 'Ortam Hava Sıcaklığı Sensörü Düşük Giriş',
  P0073: 'Ortam Hava Sıcaklığı Sensörü Yüksek Giriş',
  P0087: 'Yakıt Rayı Basıncı Çok Düşük',
  P0088: 'Yakıt Rayı Basıncı Çok Yüksek',
  P0089: 'Yakıt Basınç Regülatörü Performans',
  P0090: 'Yakıt Basınç Regülatörü Kontrol Devresi',
  P0100: 'Hava Kütlesi veya Hacimsel Akış Devresi Arızası',
  P0101: 'Hava Kütlesi veya Hacimsel Akış Devresi Aralık/Performans Sorunu',
  P0102: 'Hava Kütlesi veya Hacimsel Akış Devresi Düşük Giriş',
  P0103: 'Hava Kütlesi veya Hacimsel Akış Devresi Yüksek Giriş',
  P0104: 'Hava Kütlesi veya Hacimsel Akış Devresi Kesintili',
  P0105: 'Manifold Mutlak Basınç/Barometrik Basınç Devresi Arızası',
  P0106: 'Manifold Mutlak Basınç/Barometrik Basınç Devresi Aralık/Performans',
  P0107: 'Manifold Mutlak Basınç Devresi Düşük Giriş',
  P0108: 'Manifold Mutlak Basınç Devresi Yüksek Giriş',
  P0110: 'Emme Hava Sıcaklığı Devresi Arızası',
  P0111: 'Emme Hava Sıcaklığı Devresi Aralık/Performans',
  P0112: 'Emme Hava Sıcaklığı Devresi Düşük Giriş',
  P0113: 'Emme Hava Sıcaklığı Devresi Yüksek Giriş',
  P0115: 'Motor Soğutma Sıvısı Sıcaklığı Devresi Arızası',
  P0116: 'Motor Soğutma Sıvısı Sıcaklığı Devresi Aralık/Performans',
  P0117: 'Motor Soğutma Sıvısı Sıcaklığı Devresi Düşük Giriş',
  P0118: 'Motor Soğutma Sıvısı Sıcaklığı Devresi Yüksek Giriş',
  P0120: 'Gaz Kelebeği/Pedal Pozisyon Sensörü Devresi Arızası',
  P0121: 'Gaz Kelebeği/Pedal Pozisyon Sensörü Aralık/Performans',
  P0122: 'Gaz Kelebeği/Pedal Pozisyon Sensörü Düşük Giriş',
  P0123: 'Gaz Kelebeği/Pedal Pozisyon Sensörü Yüksek Giriş',
  P0125: 'Kapalı Çevrim Yakıt Kontrolü için Soğutma Sıvısı Sıcaklığı Yetersiz',
  P0128: 'Soğutma Sıvısı Termostatı Arızası',
  P0130: 'O2 Sensörü Devresi Arızası (Banka 1, Sensör 1)',
  P0131: 'O2 Sensörü Devresi Düşük Voltaj (Banka 1, Sensör 1)',
  P0132: 'O2 Sensörü Devresi Yüksek Voltaj (Banka 1, Sensör 1)',
  P0133: 'O2 Sensörü Yavaş Tepki (Banka 1, Sensör 1)',
  P0134: 'O2 Sensörü Devresi Aktivite Yok (Banka 1, Sensör 1)',
  P0135: 'O2 Sensörü Isıtıcı Devresi Arızası (Banka 1, Sensör 1)',
  P0136: 'O2 Sensörü Devresi Arızası (Banka 1, Sensör 2)',
  P0137: 'O2 Sensörü Devresi Düşük Voltaj (Banka 1, Sensör 2)',
  P0138: 'O2 Sensörü Devresi Yüksek Voltaj (Banka 1, Sensör 2)',
  P0139: 'O2 Sensörü Yavaş Tepki (Banka 1, Sensör 2)',
  P0140: 'O2 Sensörü Devresi Aktivite Yok (Banka 1, Sensör 2)',
  P0141: 'O2 Sensörü Isıtıcı Devresi Arızası (Banka 1, Sensör 2)',
  P0150: 'O2 Sensörü Devresi Arızası (Banka 2, Sensör 1)',
  P0151: 'O2 Sensörü Devresi Düşük Voltaj (Banka 2, Sensör 1)',
  P0152: 'O2 Sensörü Devresi Yüksek Voltaj (Banka 2, Sensör 1)',
  P0153: 'O2 Sensörü Yavaş Tepki (Banka 2, Sensör 1)',
  P0154: 'O2 Sensörü Devresi Aktivite Yok (Banka 2, Sensör 1)',
  P0155: 'O2 Sensörü Isıtıcı Devresi Arızası (Banka 2, Sensör 1)',
  P0160: 'O2 Sensörü Devresi Aktivite Yok (Banka 2, Sensör 2)',
  P0161: 'O2 Sensörü Isıtıcı Devresi Arızası (Banka 2, Sensör 2)',
  P0171: 'Sistem Çok Fakir (Banka 1)',
  P0172: 'Sistem Çok Zengin (Banka 1)',
  P0174: 'Sistem Çok Fakir (Banka 2)',
  P0175: 'Sistem Çok Zengin (Banka 2)',
  P0180: 'Yakıt Sıcaklık Sensörü Devresi Arızası',
  P0181: 'Yakıt Sıcaklık Sensörü Aralık/Performans',
  P0190: 'Yakıt Rayı Basınç Sensörü Devresi Arızası',
  P0191: 'Yakıt Rayı Basınç Sensörü Aralık/Performans',
  P0192: 'Yakıt Rayı Basınç Sensörü Düşük Giriş',
  P0193: 'Yakıt Rayı Basınç Sensörü Yüksek Giriş',
  P0201: 'Enjektör Devresi/Açık - Silindir 1',
  P0202: 'Enjektör Devresi/Açık - Silindir 2',
  P0203: 'Enjektör Devresi/Açık - Silindir 3',
  P0204: 'Enjektör Devresi/Açık - Silindir 4',
  P0205: 'Enjektör Devresi/Açık - Silindir 5',
  P0206: 'Enjektör Devresi/Açık - Silindir 6',
  P0207: 'Enjektör Devresi/Açık - Silindir 7',
  P0208: 'Enjektör Devresi/Açık - Silindir 8',
  P0215: 'Motor Durdurma Solenoid Devresi Arızası',
  P0217: 'Motor Aşırı Isınma Durumu',
  P0218: 'Şanzıman Aşırı Isınma Durumu',
  P0220: 'Gaz Kelebeği/Pedal Pozisyon Sensörü Devresi Arızası',
  P0221: 'Gaz Kelebeği/Pedal Pozisyon Sensörü Aralık/Performans',
  P0222: 'Gaz Kelebeği/Pedal Pozisyon Sensörü Düşük Giriş',
  P0223: 'Gaz Kelebeği/Pedal Pozisyon Sensörü Yüksek Giriş',
  P0230: 'Yakıt Pompası Ana Röle Devresi Arızası',
  P0231: 'Yakıt Pompası İkincil Devresi Düşük',
  P0232: 'Yakıt Pompası İkincil Devresi Yüksek',
  P0233: 'Yakıt Pompası İkincil Devresi Kesintili',
  P0234: 'Turbo/Şarj Aşırı Basınç Durumu',
  P0235: 'Turbo Basınç Sensörü Devresi Arızası',
  P0236: 'Turbo Basınç Sensörü Aralık/Performans',
  P0240: 'Turbo Basınç Sensörü Devresi Arızası (Banka 2)',
  P0241: 'Turbo Basınç Sensörü Düşük (Banka 2)',
  P0242: 'Turbo Basınç Sensörü Yüksek (Banka 2)',
  P0243: 'Turbo Atık Kapısı Solenoid Devresi',
  P0244: 'Turbo Atık Kapısı Solenoid Aralık/Performans',
  P0245: 'Turbo Atık Kapısı Solenoid Düşük',
  P0246: 'Turbo Atık Kapısı Solenoid Yüksek',
  P0261: 'Silindir 1 Enjektör Devresi Düşük',
  P0262: 'Silindir 1 Enjektör Devresi Yüksek',
  P0263: 'Silindir 1 Güç Dengesi Hatası',
  P0264: 'Silindir 2 Enjektör Devresi Düşük',
  P0265: 'Silindir 2 Enjektör Devresi Yüksek',
  P0266: 'Silindir 2 Güç Dengesi Hatası',
  P0267: 'Silindir 3 Enjektör Devresi Düşük',
  P0268: 'Silindir 3 Enjektör Devresi Yüksek',
  P0269: 'Silindir 3 Güç Dengesi Hatası',
  P0270: 'Silindir 4 Enjektör Devresi Düşük',
  P0271: 'Silindir 4 Enjektör Devresi Yüksek',
  P0272: 'Silindir 4 Güç Dengesi Hatası',
  P0300: 'Rastgele/Çoklu Silindir Ateşleme Hatası',
  P0301: 'Silindir 1 Ateşleme Hatası',
  P0302: 'Silindir 2 Ateşleme Hatası',
  P0303: 'Silindir 3 Ateşleme Hatası',
  P0304: 'Silindir 4 Ateşleme Hatası',
  P0305: 'Silindir 5 Ateşleme Hatası',
  P0306: 'Silindir 6 Ateşleme Hatası',
  P0307: 'Silindir 7 Ateşleme Hatası',
  P0308: 'Silindir 8 Ateşleme Hatası',
  P0309: 'Silindir 9 Ateşleme Hatası',
  P0310: 'Silindir 10 Ateşleme Hatası',
  P0311: 'Silindir 11 Ateşleme Hatası',
  P0312: 'Silindir 12 Ateşleme Hatası',
  P0315: 'Krank Mili Konum Sistemi Değişimi Öğrenilmedi',
  P0320: 'Ateşleme/Dağıtıcı Motor Devri Giriş Devresi Arızası',
  P0324: 'Vuruntu Sensörü Modül Hatası',
  P0325: 'Vuruntu Sensörü Devresi Arızası (Banka 1)',
  P0326: 'Vuruntu Sensörü Aralık/Performans (Banka 1)',
  P0327: 'Vuruntu Sensörü Devresi Düşük Giriş (Banka 1)',
  P0328: 'Vuruntu Sensörü Devresi Yüksek Giriş (Banka 1)',
  P0330: 'Vuruntu Sensörü Devresi Arızası (Banka 2)',
  P0335: 'Krank Mili Konum Sensörü A Devresi Arızası',
  P0336: 'Krank Mili Konum Sensörü A Devresi Aralık/Performans',
  P0337: 'Krank Mili Konum Sensörü A Devresi Düşük Giriş',
  P0338: 'Krank Mili Konum Sensörü A Devresi Yüksek Giriş',
  P0340: 'Eksantrik Mili Konum Sensörü Devresi Arızası',
  P0341: 'Eksantrik Mili Konum Sensörü Aralık/Performans',
  P0342: 'Eksantrik Mili Konum Sensörü Düşük Giriş',
  P0343: 'Eksantrik Mili Konum Sensörü Yüksek Giriş',
  P0344: 'Eksantrik Mili Konum Sensörü Kesintili',
  P0350: 'Ateşleme Bobini Birincil/İkincil Devre Arızası',
  P0351: 'Ateşleme Bobini A Birincil/İkincil Devre',
  P0352: 'Ateşleme Bobini B Birincil/İkincil Devre',
  P0353: 'Ateşleme Bobini C Birincil/İkincil Devre',
  P0354: 'Ateşleme Bobini D Birincil/İkincil Devre',
  P0355: 'Ateşleme Bobini E Birincil/İkincil Devre',
  P0356: 'Ateşleme Bobini F Birincil/İkincil Devre',
  P0365: 'Eksantrik Mili Konum Sensörü B Devresi (Banka 1)',
  P0390: 'Eksantrik Mili Konum Sensörü B Devresi (Banka 2)',
  P0400: 'Egzoz Gazı Devridaim Akış Arızası',
  P0401: 'Egzoz Gazı Devridaim Akışı Yetersiz',
  P0402: 'Egzoz Gazı Devridaim Aşırı Akış',
  P0403: 'EGR Kontrol Devresi Arızası',
  P0404: 'EGR Devresi Aralık/Performans',
  P0405: 'EGR Sensörü Düşük Giriş',
  P0406: 'EGR Sensörü Yüksek Giriş',
  P0410: 'İkincil Hava Enjeksiyon Sistemi',
  P0411: 'İkincil Hava Enjeksiyon Sistemi Yanlış Akış',
  P0420: 'Katalitik Konvertör Verimi Eşik Altı (Banka 1)',
  P0421: 'Isınma Sürecinde Katalitik Konvertör Verimi Eşik Altı (Banka 1)',
  P0422: 'Ana Katalitik Konvertör Verimi Eşik Altı (Banka 1)',
  P0430: 'Katalitik Konvertör Verimi Eşik Altı (Banka 2)',
  P0431: 'Isınma Sürecinde Katalitik Konvertör Verimi Eşik Altı (Banka 2)',
  P0432: 'Ana Katalitik Konvertör Verimi Eşik Altı (Banka 2)',
  P0440: 'Buhar Emisyon Kontrol Sistemi Arızası',
  P0441: 'Buhar Emisyon Kontrol Sistemi Yanlış Saflaştırma Akışı',
  P0442: 'Buhar Emisyon Sistemi Küçük Sızıntı Tespiti',
  P0443: 'Buhar Emisyon Sistemi Saflaştırma Kontrol Devresi',
  P0444: 'Buhar Emisyon Sistemi Saflaştırma Devresi Açık',
  P0445: 'Buhar Emisyon Sistemi Saflaştırma Devresi Kısa Devre',
  P0451: 'Buhar Emisyon Sistemi Basınç Sensörü Aralık/Performans',
  P0452: 'Buhar Emisyon Sistemi Basınç Sensörü Düşük Giriş',
  P0453: 'Buhar Emisyon Sistemi Basınç Sensörü Yüksek Giriş',
  P0454: 'Buhar Emisyon Sistemi Basınç Sensörü Kesintili',
  P0455: 'Buhar Emisyon Sistemi Büyük Sızıntı Tespiti',
  P0456: 'Buhar Emisyon Sistemi Çok Küçük Sızıntı Tespiti',
  P0460: 'Yakıt Seviye Sensörü Devresi Arızası',
  P0461: 'Yakıt Seviye Sensörü Aralık/Performans',
  P0462: 'Yakıt Seviye Sensörü Düşük Giriş',
  P0463: 'Yakıt Seviye Sensörü Yüksek Giriş',
  P0464: 'Yakıt Seviye Sensörü Kesintili',
  P0480: 'Soğutma Fanı Röle 1 Kontrol Devresi',
  P0481: 'Soğutma Fanı Röle 2 Kontrol Devresi',
  P0483: 'Soğutma Fanı Doğrulama Hatası',
  P0500: 'Araç Hız Sensörü Arızası',
  P0501: 'Araç Hız Sensörü Aralık/Performans',
  P0502: 'Araç Hız Sensörü Düşük Giriş',
  P0503: 'Araç Hız Sensörü Kesintili/Yüksek',
  P0505: 'Rölanti Kontrol Sistemi Arızası',
  P0506: 'Rölanti Kontrol Sistemi Devri Çok Düşük',
  P0507: 'Rölanti Kontrol Sistemi Devri Çok Yüksek',
  P0510: 'Kapalı Gaz Kelebeği Pozisyon Anahtarı Arızası',
  P0520: 'Motor Yağ Basınç Sensörü Devresi',
  P0521: 'Motor Yağ Basınç Sensörü Aralık/Performans',
  P0522: 'Motor Yağ Basınç Sensörü Düşük Voltaj',
  P0523: 'Motor Yağ Basınç Sensörü Yüksek Voltaj',
  P0530: 'A/C Soğutucu Basınç Sensörü',
  P0550: 'Hidrolik Direksiyon Basınç Sensörü',
  P0560: 'Sistem Voltajı Arızası',
  P0562: 'Sistem Voltajı Düşük',
  P0563: 'Sistem Voltajı Yüksek',
  P0571: 'Fren Anahtar Devresi Arızası',
  P0600: 'Seri İletişim Bağlantı Arızası',
  P0601: 'Dahili Kontrol Modülü Hafıza Sağlama Toplamı Hatası',
  P0602: 'Kontrol Modülü Programlama Hatası',
  P0603: 'Dahili Kontrol Modülü RAM Hatası',
  P0604: 'Dahili Kontrol Modülü Rastgele Erişim Bellek (RAM) Hatası',
  P0605: 'Dahili Kontrol Modülü ROM Hatası',
  P0606: 'ECM/PCM İşlemci Hatası',
  P0607: 'Kontrol Modülü Performansı',
  P0610: 'Kontrol Modülü Seçenek Hatası',
  P0620: 'Jeneratör Kontrol Devresi',
  P0622: 'Jeneratör Alan Sargı Devresi',
  P0645: 'A/C Kompresör Röle Devresi',
  P0646: 'A/C Kompresör Röle Devresi Düşük',
  P0647: 'A/C Kompresör Röle Devresi Yüksek',
  P0650: 'Arıza Gösterge Lambası (MIL) Kontrol Devresi',
  P0654: 'Motor Devri Gösterge Çıkış Devresi',
  P0660: 'Emme Manifoldu Ayarlama Valf Kontrol Devresi',
  P0671: 'Kızdırma Buşi Devresi Silindir 1',
  P0672: 'Kızdırma Buşi Devresi Silindir 2',
  P0673: 'Kızdırma Buşi Devresi Silindir 3',
  P0674: 'Kızdırma Buşi Devresi Silindir 4',
  P0685: 'ECM/PCM Güç Röle Kontrol Devresi',
  P0686: 'ECM/PCM Güç Röle Devresi Düşük',
  P0687: 'ECM/PCM Güç Röle Devresi Yüksek',
  P0700: 'Şanzıman Kontrol Sistemi Arızası',
  P0701: 'Şanzıman Kontrol Sistemi Aralık/Performans',
  P0702: 'Şanzıman Kontrol Sistemi Elektriksel',
  P0703: 'Fren Anahtar Devresi B Arızası',
  P0704: 'Debriyaj Anahtarı Giriş Devresi',
  P0705: 'Vites Aralık Sensörü Devresi Arızası (PRNDL Giriş)',
  P0706: 'Vites Aralık Sensörü Aralık/Performans',
  P0707: 'Vites Aralık Sensörü Düşük Giriş',
  P0708: 'Vites Aralık Sensörü Yüksek Giriş',
  P0710: 'Şanzıman Yağ Sıcaklık Sensörü',
  P0711: 'Şanzıman Yağ Sıcaklık Sensörü Aralık/Performans',
  P0712: 'Şanzıman Yağ Sıcaklık Sensörü Düşük',
  P0713: 'Şanzıman Yağ Sıcaklık Sensörü Yüksek',
  P0715: 'Giriş/Türbin Hız Sensörü Devresi',
  P0716: 'Giriş/Türbin Hız Sensörü Aralık/Performans',
  P0717: 'Giriş/Türbin Hız Sensörü Sinyal Yok',
  P0720: 'Çıkış Hız Sensörü Devresi',
  P0721: 'Çıkış Hız Sensörü Aralık/Performans',
  P0722: 'Çıkış Hız Sensörü Sinyal Yok',
  P0723: 'Çıkış Hız Sensörü Kesintili',
  P0724: 'Fren Anahtar Devresi B Yüksek',
  P0725: 'Motor Devri Giriş Devresi',
  P0730: 'Yanlış Vites Oranı',
  P0731: 'Vites 1 Yanlış Oran',
  P0732: 'Vites 2 Yanlış Oran',
  P0733: 'Vites 3 Yanlış Oran',
  P0734: 'Vites 4 Yanlış Oran',
  P0735: 'Vites 5 Yanlış Oran',
  P0736: 'Geri Vites Yanlış Oran',
  P0737: 'TCM Motor Hızı Çıkış Devresi',
  P0738: 'TCM Motor Hızı Çıkış Devresi Düşük',
  P0739: 'TCM Motor Hızı Çıkış Devresi Yüksek',
  P0740: 'Tork Konvertörü Debriyaj Devresi',
  P0741: 'Tork Konvertörü Debriyaj Devresi Performans/Kilitlenme Yok',
  P0742: 'Tork Konvertörü Debriyaj Devresi Sürekli Kilitli',
  P0743: 'Tork Konvertörü Debriyaj Devresi Elektriksel',
  P0748: 'Basınç Kontrol Solenoid Devresi Elektriksel',
  P0750: 'Vites Solenoid A Arızası',
  P0751: 'Vites Solenoid A Performans/Kapalı',
  P0752: 'Vites Solenoid A Sürekli Açık',
  P0753: 'Vites Solenoid A Elektriksel',
  P0755: 'Vites Solenoid B Arızası',
  P0756: 'Vites Solenoid B Performans',
  P0757: 'Vites Solenoid B Sürekli Açık',
  P0758: 'Vites Solenoid B Elektriksel',
  P0760: 'Vites Solenoid C Arızası',
  P0761: 'Vites Solenoid C Performans',
  P0762: 'Vites Solenoid C Sürekli Açık',
  P0763: 'Vites Solenoid C Elektriksel',
  P0765: 'Vites Solenoid D Arızası',
  P0770: 'Vites Solenoid E Arızası',
  P0775: 'Basınç Kontrol Solenoid B',
  P0780: 'Vites Değiştirme Arızası',
  P0785: 'Vites Zamanlama Solenoidi',
  P0790: 'Normal/Performans Vites Devresi',
  P0801: 'Geri Vites Engelleyici Devresi',
  P0850: 'Park/Nötr Anahtar Giriş Devresi',
  P1000: 'OBD-II Test İzleme Tamamlanmadı',
  P1100: 'Hava Kütle Sensörü Kesintili',
  P1101: 'Hava Kütle Sensörü Aralık Dışı',
  P1110: 'Emme Hava Sıcaklığı Kesintili',
  P1120: 'Gaz Kelebeği Pozisyon Sensörü Devresi',
  P1125: 'Gaz Kelebeği Pozisyon Sensörü Kesintili',
  P1130: 'HO2S Isıtıcı Devresi (Banka 1, Sensör 1)',
  P1135: 'HO2S Isıtıcı Devresi (Banka 1, Sensör 2)',
  P1155: 'HO2S Isıtıcı Devresi (Banka 2, Sensör 1)',
  P1170: 'Isıtmalı O2 Sensörü 1 Isıtıcı Devresi',
  P1180: 'Yakıt Sıcaklık Sensörü Devresi',
  P1190: 'Yakıt Basınç Regülatörü',
  P1195: 'Turbo Basınç Sensörü',
  P1220: 'Yakıt Pompası Kontrol Devresi',
  P1230: 'Yakıt Pompası Röle Devresi',
  P1240: 'Gaz Kelebeği Motoru',
  P1250: 'Yakıt Pompası Kontrol Devresi',
  P1300: 'Ateşleme Zamanlaması Ayar Devresi',
  P1310: 'Ateşleme Kontrol Modülü',
  P1320: 'Ateşleme Sinyali',
  P1335: 'Krank Mili Pozisyon Sensörü Devresi',
  P1340: 'Eksantrik Mili Pozisyon Sensörü Devresi',
  P1345: 'Krank-Eksantrik Mili Pozisyon Uyumsuzluğu',
  P1350: 'Ateşleme Kontrol Sistemi',
  P1360: 'Ateşleme Bobini Kontrolü',
  P1380: 'ABS - Ateşleme Bağlantısı',
  P1400: 'EGR Devresi Arızası',
  P1401: 'EGR Devresi Yüksek Sıcaklık',
  P1410: 'EGR Basınç Sensörü',
  P1440: 'EVAP Canister Tahliye Solenoidi',
  P1441: 'EVAP Kontrol Sistemi Sızıntı',
  P1442: 'EVAP Vakum Sistemi',
  P1450: 'Yakıt Tankı Vakum Tahliye Edilemiyor',
  P1451: 'EVAP Sistemi Basınç Sensörü',
  P1460: 'Isıtmalı Yataklı Katalitik Konvertör',
  P1470: 'EGR Sıcaklık Sensörü',
  P1480: 'Katalitik Konvertör Sıcaklık Sensörü',
  P1490: 'EGR Vakum Regülatör Solenoidi',
  P1500: 'Araç Hız Sensörü Devresi',
  P1501: 'Araç Hız Sensörü Kesintili',
  P1510: 'Rölanti Hava Kontrol Aktüatör Devresi',
  P1520: 'Park/Nötr Anahtar Devresi',
  P1530: 'Klima Soğutucu Basınç Sensörü',
  P1531: 'Klima Soğutucu Düşük',
  P1540: 'Hava-Yakıt Oranı Sensörü',
  P1550: 'Hız Sabitleyici Sistemi',
  P1560: 'Hız Sabitleyici Fren Anahtarı',
  P1570: 'Hız Sabitleyici Kontrol Devresi',
  P1600: 'ECM Batarya Devresi',
  P1601: 'ECM İletişim Hatası',
  P1610: 'Dahili ECM Hatası',
  P1611: 'ECM Flaş Bellek Hatası',
  P1620: 'Sistem Güvenlik ECM Verisi',
  P1621: 'Kontrol Modülü Uzun Ömürlü Bellek',
  P1630: 'Hırsızlık Önleme Sistemi Arızası',
  P1631: 'Hırsızlık Önleme Anahtar Kodu Yanlış',
  P1640: 'Motor Kontrol Modülü Arızası',
  P1645: 'EGR Solenoid Devresi',
  P1650: 'Hidrolik Direksiyon Basınç Anahtarı',
  P1651: 'Hidrolik Direksiyon Basınç Sensörü',
  P1660: 'ECM Güç Rölesi',
  P1670: 'ECM Veri Bağlantısı',
  P1680: 'Gaz Kelebeği Pozisyon Sensörü',
  P1690: 'Atık Kapısı Solenoidi',
  P1700: 'Şanzıman Sistemi Arızası',
  P1701: 'Şanzıman Güç Devresi',
  P1705: 'Şanzıman Vites Sensörü',
  P1710: 'Şanzıman Yağ Sıcaklık Sensörü',
  P1711: 'Şanzıman Yağ Sıcaklık Sensörü Aralık/Performans',
  P1720: 'Şanzıman Hız Sensörü',
  P1730: 'Şanzıman Vites Oranı',
  P1740: 'Tork Konvertörü Debriyaj',
  P1750: 'Şanzıman Basınç Kontrolü',
  P1760: 'Şanzıman Solenoid Devresi',
  P1770: 'Şanzıman Kilitleme',
  P1780: 'Şanzıman Kontrol Rölesi',
  P1790: 'Şanzıman Arıza Gösterge Işığı',
  P1800: 'Dört Teker Çekiş Kontrolü',
  P1810: 'Transfer Kutusu Motoru',
  P1820: 'Dört Teker Çekiş Sensörü',
  P1830: 'Transfer Kutusu Debriyaj',
  P1840: 'Aktarma Kutusu Devresi',
  P1850: 'Dört Teker Çekiş Kilitleme',
  P1890: 'Şanzıman ECU Arızası',
  P2000: 'NOx Hacim Aşımı',
  P2001: 'NOx Hacim Aşımı (Banka 2)',
  P2002: 'Dizel Partikül Filtresi Verimi (Banka 1)',
  P2010: 'Emme Manifoldu Ayarlama Valfi (Banka 2)',
  P2015: 'Emme Manifoldu Konum Sensörü',
  P2020: 'Emme Manifoldu Ayarlama Valfi Devresi',
  P2030: 'Yakıt Seviyesi Gösterge Sensörü',
  P2040: 'Yakıt Isıtıcı Devresi',
  P2041: 'Yakıt Isıtıcı Devresi Düşük',
  P2042: 'Yakıt Isıtıcı Devresi Yüksek',
  P2043: 'Yakıt Isıtıcı Sıcaklık Sensörü',
  P2050: 'Dizel Partikül Filtresi Sıcaklık Sensörü',
  P2060: 'Yakıt Seviyesi Gösterge Devresi',
  P2070: 'Emme Manifoldu Ayarlama Valfi (Açık/Sürekli)',
  P2080: 'EGR Sıcaklık Sensörü Devresi',
  P2090: 'B Yakıt Enjeksiyon Zamanlaması',
  P2100: 'Gaz Kelebeği Aktüatör Motor Devresi',
  P2101: 'Gaz Kelebeği Aktüatör Kontrol Motoru Aralık/Performans',
  P2102: 'Gaz Kelebeği Aktüatör Motor Devresi Düşük',
  P2103: 'Gaz Kelebeği Aktüatör Motor Devresi Yüksek',
  P2110: 'Gaz Kelebeği Aktüatör Sistemi - Kısıtlı',
  P2111: 'Gaz Kelebeği Aktüatör Sistemi - Sürekli Açık',
  P2112: 'Gaz Kelebeği Aktüatör Sistemi - Sürekli Kapalı',
  P2119: 'Gaz Kelebeği Aktüatör Aralık/Performans',
  P2120: 'Gaz Kelebeği/Pedal Pozisyon Sensörü D Devresi',
  P2121: 'Gaz Kelebeği/Pedal Pozisyon Sensörü D Aralık/Performans',
  P2122: 'Gaz Kelebeği/Pedal Pozisyon Sensörü D Düşük Giriş',
  P2123: 'Gaz Kelebeği/Pedal Pozisyon Sensörü D Yüksek Giriş',
  P2125: 'Gaz Kelebeği/Pedal Pozisyon Sensörü E Devresi',
  P2127: 'Gaz Kelebeği/Pedal Pozisyon Sensörü E Düşük Giriş',
  P2128: 'Gaz Kelebeği/Pedal Pozisyon Sensörü E Yüksek Giriş',
  P2135: 'Gaz Kelebeği/Pedal Pozisyon Sensörü D-E Voltaj Uyumsuzluğu',
  P2138: 'Gaz Kelebeği/Pedal Pozisyon Sensörü D-E Voltaj Uyumsuzluğu',
  P2140: 'EGR Valfi Konum Sensörü',
  P2141: 'EGR Valfi Kontrol Devresi Düşük',
  P2142: 'EGR Valfi Kontrol Devresi Yüksek',
  P2146: 'Enjektör Devresi (Sıra 1)',
  P2151: 'Araç Hız Sensörü',
  P2155: 'Yakıt Sıcaklık Sensörü',
  P2160: 'Araç Hız Sensörü Çıkış Devresi',
  P2170: 'Klima Kontrol Devresi',
  P2176: 'Gaz Kelebeği Aktüatör Öğrenme Pozisyonu',
  P2180: 'Soğutma Sıvısı Sıcaklık Sensörü',
  P2181: 'Soğutma Sistemi Performansı',
  P2185: 'EGR Sıcaklık Sensörü',
  P2187: 'Sistem Çok Fakir Rölantide (Banka 1)',
  P2188: 'Sistem Çok Zengin Rölantide (Banka 1)',
  P2195: 'O2 Sensörü Sinyali Fakir/Kararlı (Banka 1, Sensör 1)',
  P2196: 'O2 Sensörü Sinyali Zengin/Kararlı (Banka 1, Sensör 1)',
  P2197: 'O2 Sensörü Sinyali Fakir/Kararlı (Banka 2, Sensör 1)',
  P2198: 'O2 Sensörü Sinyali Zengin/Kararlı (Banka 2, Sensör 1)',
  P2200: 'NOx Sensörü Devresi (Banka 1)',
  P2220: 'Barometrik Basınç Sensörü',
  P2227: 'Barometrik Basınç Sensörü Aralık/Performans',
  P2228: 'Barometrik Basınç Sensörü Düşük',
  P2229: 'Barometrik Basınç Sensörü Yüksek',
  P2230: 'Barometrik Basınç Sensörü Kesintili',
  P2231: 'O2 Sensörü Sinyal Devresi (Banka 1, Sensör 1)',
  P2237: 'O2 Sensörü Pozitif Akım Kontrol Devresi (Banka 1, Sensör 1)',
  P2240: 'O2 Sensörü Pozitif Akım Kontrol Devresi (Banka 2, Sensör 1)',
  P2251: 'O2 Sensörü Negatif Akım Kontrol Devresi (Banka 1, Sensör 1)',
  P2261: 'Turbo Şarj Mekanik Arıza',
  P2262: 'Turbo Basıncı Beklenmiyor',
  P2270: 'O2 Sensörü Sinyal Fakir/Kararlı (Banka 1, Sensör 2)',
  P2280: 'Yakıt Basınç Regülatörü Kontrol Devresi',
  P2290: 'Yakıt Basıncı Çok Düşük',
  P2291: 'Yakıt Basıncı Çok Düşük - Motor Çalışıyor',
  P2292: 'Yakıt Basınç Regülatörü',
  P2293: 'Yakıt Basınç Regülatörü Performans',
  P2294: 'Yakıt Basınç Regülatörü Kontrol Devresi',
  P2295: 'Yakıt Basınç Regülatörü Kontrol Devresi Düşük',
  P2296: 'Yakıt Basınç Regülatörü Kontrol Devresi Yüksek',
  P2300: 'Ateşleme Bobini A Kontrol Devresi Düşük',
  P2301: 'Ateşleme Bobini A Kontrol Devresi Yüksek',
  P2302: 'Ateşleme Bobini B Kontrol Devresi Düşük',
  P2303: 'Ateşleme Bobini B Kontrol Devresi Yüksek',
  P2304: 'Ateşleme Bobini C Kontrol Devresi Düşük',
  P2305: 'Ateşleme Bobini C Kontrol Devresi Yüksek',
  P2400: 'Yakıt Sızıntı Tespit Pompası Devresi',
  P2401: 'Yakıt Sızıntı Tespit Pompası Devresi Düşük',
  P2402: 'Yakıt Sızıntı Tespit Pompası Devresi Yüksek',
  P2413: 'EGR Sistemi Performans',
  P2420: 'EVAP Tahliye Solenoidi Devresi',
  P2421: 'EVAP Tahliye Solenoidi Açık',
  P2440: 'İkincil Hava Enjeksiyon Sistemi Değiştirme Valfi',
  P2500: 'Jeneratör Lamba Devresi Düşük',
  P2501: 'Jeneratör Lamba Devresi Yüksek',
  P2502: 'Şarj Sistemi Voltajı',
  P2503: 'Şarj Sistemi Düşük Voltaj',
  P2504: 'Şarj Sistemi Yüksek Voltaj',
  P2600: 'Soğutma Fanı Kontrol Devresi',
  P2601: 'Soğutma Fanı Kontrol Devresi Aralık/Performans',
  P2602: 'Soğutma Fanı Kontrol Devresi Düşük',
  P2603: 'Soğutma Fanı Kontrol Devresi Yüksek',
  P2610: 'ECM/PCM Motor Kapatma Zamanlayıcısı',
  P2620: 'Gaz Kelebeği Pozisyon Sensörü Öğrenme',
  P2635: 'Yakıt Pompası Akımı',
  P2640: 'Turbo Şarj Kontrol Devresi',
  P2700: 'Şanzıman Vites Solenoidi Performans (Sıra 2)',
  P2710: 'Basınç Kontrol Solenoidi',
  P2711: 'Şanzıman Vites Değiştirme Arızası',
  P2720: 'Basınç Kontrol Solenoidi B',
  P2721: 'Basınç Kontrol Solenoidi B Performans',
  P2722: 'Basınç Kontrol Solenoidi B Düşük',
  P2730: 'Basınç Kontrol Solenoidi C',
  P2740: 'Şanzıman Yağ Sıcaklık Sensörü',
  P2750: 'Tork Konvertörü Debriyaj Devresi',
  P2760: 'Tork Konvertörü Debriyaj Devresi Performans',
  P2770: 'Tork Konvertörü Debriyaj Solenoidi',
  P2780: 'Şanzıman Vites Adaptasyonu',
  P2790: 'Şanzıman Kilitleme Solenoidi',
  P2800: 'Şanzıman Vites Sensörü Devresi',
  P2810: 'Basınç Kontrol Solenoidi D',
  P2820: 'Basınç Kontrol Solenoidi E',
  U0001: 'Yüksek Hızlı CAN İletişim Bus',
  U0002: 'Yüksek Hızlı CAN İletişim Bus Performans',
  U0003: 'Yüksek Hızlı CAN İletişim Bus + Kapalı',
  U0010: 'Orta Hız CAN İletişim Bus',
  U0020: 'Düşük Hız CAN İletişim Bus',
  U0073: 'Kontrol Modülü İletişim Bus Kapalı',
  U0100: 'ECM/PCM A ile İletişim Kaybı',
  U0101: 'TCM ile İletişim Kaybı',
  U0102: 'Transfer Kutusu Kontrol Modülü ile İletişim Kaybı',
  U0103: 'Vites Kontrol Modülü ile İletişim Kaybı',
  U0104: 'Hız Sabitleyici Modülü ile İletişim Kaybı',
  U0105: 'Yakıt Enjeksiyon Modülü ile İletişim Kaybı',
  U0106: 'Glow Plug Modülü ile İletişim Kaybı',
  U0107: 'Gaz Kelebeği Aktüatör Modülü ile İletişim Kaybı',
  U0108: 'Alternatör Kontrol Modülü ile İletişim Kaybı',
  U0109: 'Yakıt Pompası Modülü ile İletişim Kaybı',
  U0110: 'Sürüş Motoru Kontrol Modülü ile İletişim Kaybı',
  U0111: 'Batarya Enerji Yönetim Modülü ile İletişim Kaybı',
  U0112: 'Batarya Şarj Modülü ile İletişim Kaybı',
  U0113: 'Emisyon Kontrol Modülü ile İletişim Kaybı',
  U0114: 'Dört Teker Çekiş Modülü ile İletişim Kaybı',
  U0115: 'ECM B ile İletişim Kaybı',
  U0120: 'SCM (Aktif Süspansiyon) ile İletişim Kaybı',
  U0121: 'ABS Kontrol Modülü ile İletişim Kaybı',
  U0122: 'DSC (Dinamik Stabilite) Modülü ile İletişim Kaybı',
  U0123: 'ESP Modülü ile İletişim Kaybı',
  U0124: 'TPMS Modülü ile İletişim Kaybı',
  U0125: 'Çok Eksenli Hız Sensörü ile İletişim Kaybı',
  U0126: 'Direksiyon Açı Sensörü ile İletişim Kaybı',
  U0127: 'Basınç Sensörü ile İletişim Kaybı',
  U0128: 'Park Freni Modülü ile İletişim Kaybı',
  U0129: 'Fren Sistemi Modülü ile İletişim Kaybı',
  U0130: 'Dört Teker Direksiyon Modülü ile İletişim Kaybı',
  U0131: 'Hidrolik Direksiyon Modülü ile İletişim Kaybı',
  U0132: 'Süspansiyon Seviye Modülü ile İletişim Kaybı',
  U0133: 'Hız Sabitleyici Uzak Modülü ile İletişim Kaybı',
  U0134: 'Hız Sabitleyici Fren Modülü ile İletişim Kaybı',
  U0135: 'Koltuk Hafıza Modülü ile İletişim Kaybı',
  U0136: 'Ayna Kontrol Modülü ile İletişim Kaybı',
  U0137: 'Römork Kontrol Modülü ile İletişim Kaybı',
  U0138: 'Araç Römork Modülü ile İletişim Kaybı',
  U0139: 'Süspansiyon Kontrol Modülü B ile İletişim Kaybı',
  U0140: 'Gövde Kontrol Modülü ile İletişim Kaybı',
  U0141: 'Gövde Kontrol Modülü A ile İletişim Kaybı',
  U0142: 'Gövde Kontrol Modülü B ile İletişim Kaybı',
  U0143: 'Gövde Kontrol Modülü C ile İletişim Kaybı',
  U0144: 'Gövde Kontrol Modülü D ile İletişim Kaybı',
  U0145: 'Gövde Kontrol Modülü E ile İletişim Kaybı',
  U0146: 'Kapı Kontrol Modülü ile İletişim Kaybı',
  U0147: 'Kapı Kontrol Modülü A ile İletişim Kaybı',
  U0148: 'Kapı Kontrol Modülü B ile İletişim Kaybı',
  U0149: 'Sürücü Kapı Modülü ile İletişim Kaybı',
  U0150: 'GPS Modülü ile İletişim Kaybı',
  U0151: 'SRS (Hava Yastığı) Modülü ile İletişim Kaybı',
  U0152: 'SRS Sağ Sensör ile İletişim Kaybı',
  U0153: 'SRS Sol Sensör ile İletişim Kaybı',
  U0154: 'SRS Arka Sensör ile İletişim Kaybı',
  U0155: 'Gösterge Paneli ile İletişim Kaybı',
  U0156: 'Merkezi Bilgi Modülü ile İletişim Kaybı',
  U0157: 'Ses Kontrol Modülü ile İletişim Kaybı',
  U0158: 'Navigasyon Modülü ile İletişim Kaybı',
  U0159: 'Telefon Modülü ile İletişim Kaybı',
  U0160: 'Sesli Komut Modülü ile İletişim Kaybı',
  U0161: 'Mikrofon Modülü ile İletişim Kaybı',
  U0162: 'TV Modülü ile İletişim Kaybı',
  U0163: 'Ekran Modülü ile İletişim Kaybı',
  U0164: 'HVAC Kontrol Modülü ile İletişim Kaybı',
  U0165: 'Isıtma Modülü ile İletişim Kaybı',
  U0166: 'Klima Modülü ile İletişim Kaybı',
  U0167: 'Araç Güvenlik Modülü ile İletişim Kaybı',
  U0168: 'Erişim Kontrol Modülü ile İletişim Kaybı',
  U0169: 'Güneşlik Kontrol Modülü ile İletişim Kaybı',
  U0170: 'Acil Çağrı Modülü ile İletişim Kaybı',
  U0180: 'Far Kontrol Modülü ile İletişim Kaybı',
  U0190: 'Yağmur Sensörü Modülü ile İletişim Kaybı',
  U0200: 'Yolcu Kapı Modülü ile İletişim Kaybı',
  U0210: 'Arka Sol Kapı Modülü ile İletişim Kaybı',
  U0220: 'Arka Sağ Kapı Modülü ile İletişim Kaybı',
  U0230: 'Bagaj Modülü ile İletişim Kaybı',
  U0240: 'Araç Radyo Modülü ile İletişim Kaybı',
  U0250: 'Ses Yükseltici Modülü ile İletişim Kaybı',
  U0260: 'Kamera Modülü ile İletişim Kaybı',
  U0270: 'Görüş Kontrol Modülü ile İletişim Kaybı',
  U0280: 'Hız Sabitleyici Radar ile İletişim Kaybı',
  U0290: 'Motor Soğutma Fanı Modülü ile İletişim Kaybı',
  U0300: 'Dahili Kontrol Modülü Yazılım Uyumsuzluğu',
  U1000: 'CAN İletişim Ağı Arızası',
  U1100: 'Motor Kontrol Modülü ile İletişim Kaybı',
  U1200: 'Şanzıman Kontrol Modülü ile İletişim Kaybı',
  U1300: 'ABS Modülü ile İletişim Kaybı',
  U1400: 'Gösterge Paneli ile İletişim Kaybı',
  C0000: 'Araç Hız Sensörü - Sol Ön',
  C0010: 'Araç Hız Sensörü - Sağ Ön',
  C0011: 'ABS Hidrolik Pompa Devresi',
  C0012: 'ABS Hidrolik Pompa Devresi Düşük',
  C0020: 'Araç Hız Sensörü - Sol Arka',
  C0021: 'Fren Basınç Sensörü',
  C0022: 'Fren Basınç Sensörü Düşük',
  C0030: 'Araç Hız Sensörü - Sağ Arka',
  C0035: 'ABS Sensörü - Sol Ön',
  C0040: 'Fren Sistemi Arızası',
  C0041: 'Fren Hidrolik Basıncı',
  C0042: 'Fren Hidrolik Basıncı Düşük',
  C0045: 'ABS Sistemi Arızası',
  C0046: 'ABS Sistemi Pompa Motoru',
  C0050: 'ESP/ESC Sistemi Arızası',
  C0051: 'ESP Basınç Sensörü',
  C0060: 'Stabilite Kontrol Sistemi',
  C0070: 'Çekiş Kontrol Sistemi',
  C0080: 'Fren Destek Sistemi',
  C0090: 'Hidrolik Fren Yardımı',
  C0100: 'Park Freni Arızası',
  C0101: 'Park Freni Devresi',
  C0102: 'Park Freni Aktüatörü',
  C0110: 'Süspansiyon Kontrolü',
  C0120: 'Yükseklik Sensörü',
  C0130: 'Süspansiyon Basınç Sensörü',
  C0140: 'Süspansiyon Valfi',
  C0150: 'Direksiyon Açı Sensörü',
  C0151: 'Direksiyon Açı Sensörü Aralık/Performans',
  C0160: 'Direksiyon Tork Sensörü',
  C0161: 'Direksiyon Tork Sensörü Aralık/Performans',
  C0170: 'Hidrolik Direksiyon Sistemi',
  C0171: 'Hidrolik Direksiyon Pompası',
  C0172: 'Hidrolik Direksiyon Basıncı',
  C0200: 'Hava Yastığı Sistemi',
  C0201: 'Hava Yastığı Sürücü Devresi',
  C0202: 'Hava Yastığı Yolcu Devresi',
  C0203: 'Hava Yastığı Yan Devresi',
  C0204: 'Hava Yastığı Perde Devresi',
  C0210: 'Emniyet Kemeri Gergici',
  C0211: 'Emniyet Kemeri Sensörü',
  C0220: 'Darbe Sensörü',
  C0221: 'Yanal Darbe Sensörü',
  C0230: 'Emniyet Kemeri Uyarı Sistemi',
  C0240: 'Yolcu Algılama Sensörü',
  C0250: 'Aktif Başlık Desteği',
  C0300: 'Dört Teker Çekiş Sistemi',
  C0301: 'Dört Teker Çekiş Debriyaj',
  C0302: 'Dört Teker Çekiş Transfer Kutusu',
  C0303: 'Dört Teker Çekiş Motoru',
  C0304: 'Dört Teker Çekiş Sensörü',
  C0310: 'Transfer Kutusu Kilitleme',
  C0320: 'Arka Diferansiyel Kilidi',
  C0330: 'Ön Diferansiyel Kilidi',
  C0400: 'Hız Sabitleyici Sistemi',
  C0401: 'Hız Sabitleyici Aktüatör',
  C0402: 'Hız Sabitleyici Fren Anahtarı',
  C0403: 'Hız Sabitleyici Kontrol',
  C0410: 'Hız Sabitleyici Radar',
  C0500: 'Lastik Basınç Sistemi',
  C0501: 'Lastik Basınç Sensörü - Sol Ön',
  C0502: 'Lastik Basınç Sensörü - Sağ Ön',
  C0503: 'Lastik Basınç Sensörü - Sol Arka',
  C0504: 'Lastik Basınç Sensörü - Sağ Arka',
  C0505: 'Lastik Basınç Sistemi Verici',
  C0510: 'Lastik Basınç Gösterge Işığı',
  B0000: 'Hava Yastığı Sistemi Arızası',
  B0010: 'Sürücü Ön Kademe 1 Açılma Kontrolü',
  B0011: 'Sürücü Ön Kademe 2 Açılma Kontrolü',
  B0012: 'Sürücü Ön Kademe 1 Açılma Direnci Düşük',
  B0013: 'Sürücü Ön Kademe 2 Açılma Direnci Düşük',
  B0020: 'Yolcu Ön Kademe 1 Açılma Kontrolü',
  B0021: 'Yolcu Ön Kademe 2 Açılma Kontrolü',
  B0022: 'Yolcu Ön Açılma Direnci Düşük',
  B0030: 'Sürücü Yan Hava Yastığı Açılma Kontrolü',
  B0040: 'Yolcu Yan Hava Yastığı Açılma Kontrolü',
  B0050: 'Perde Hava Yastığı Açılma Kontrolü',
  B0051: 'Perde Hava Yastığı Direnci Düşük',
  B0060: 'Emniyet Kemeri Gergici Sürücü',
  B0061: 'Emniyet Kemeri Gergici Yolcu',
  B0070: 'Koltuk Pozisyon Sensörü',
  B0071: 'Koltuk Pozisyon Sensörü Aralık/Performans',
  B0080: 'Yolcu Sınıflandırma Sistemi',
  B0081: 'Yolcu Sınıflandırma Sensörü',
  B0090: 'Darbe Sensörü - Ön Sol',
  B0091: 'Darbe Sensörü - Ön Sağ',
  B0092: 'Darbe Sensörü - Yan Sol',
  B0093: 'Darbe Sensörü - Yan Sağ',
  B0100: 'Gövde Kontrol Modülü Arızası',
  B0101: 'Gövde Kontrol Modülü Hafıza',
  B0102: 'Gövde Kontrol Modülü Güç',
  B0110: 'Merkezi Kilit Sistemi',
  B0111: 'Merkezi Kilit Motoru - Sürücü',
  B0112: 'Merkezi Kilit Motoru - Yolcu',
  B0120: 'Aydınlatma Kontrolü',
  B0121: 'İç Aydınlatma Devresi',
  B0122: 'Far Kontrol Devresi',
  B0130: 'Silecek Kontrol Sistemi',
  B0131: 'Ön Silecek Motoru',
  B0132: 'Arka Silecek Motoru',
  B0133: 'Silecek Yağmur Sensörü',
  B0140: 'Cam Kontrol Sistemi',
  B0141: 'Elektrikli Cam - Sürücü',
  B0142: 'Elektrikli Cam - Yolcu',
  B0143: 'Elektrikli Cam - Arka Sol',
  B0144: 'Elektrikli Cam - Arka Sağ',
  B0150: 'Ayna Kontrol Sistemi',
  B0151: 'Yan Ayna Motoru - Sol',
  B0152: 'Yan Ayna Motoru - Sağ',
  B0160: 'Klima Kontrol Sistemi',
  B0161: 'İç Sıcaklık Sensörü',
  B0162: 'Dış Sıcaklık Sensörü',
  B0163: 'Güneş Sensörü',
  B0164: 'Klima Fan Motoru',
  B0170: 'Isıtmalı Koltuk Kontrolü',
  B0171: 'Isıtmalı Koltuk - Sürücü',
  B0172: 'Isıtmalı Koltuk - Yolcu',
  B0180: 'Hafıza Koltuk Kontrolü',
  B0181: 'Hafıza Koltuk - Sürücü',
  B0182: 'Hafıza Koltuk Konum Sensörü',
  B0190: 'Römork Aydınlatma Sistemi',
  B0200: 'Çekme Paketi Modülü',

  P0423: 'Katalitik Konvertör Verimi Eşik Altı (Isıtma) (Banka 1)',
  P0424: 'Katalitik Konvertör Sıcaklığı Eşik Altı (Banka 1)',
  P0446: 'Buhar Emisyon Kontrol Sistemi Havalandırma Kontrol Devresi',
  P0447: 'Buhar Emisyon Kontrol Sistemi Havalandırma Kontrol Devresi Açık',
  P0448: 'Buhar Emisyon Kontrol Sistemi Havalandırma Kontrol Devresi Kısa Devre',
  P0449: 'Buhar Emisyon Kontrol Sistemi Havalandırma Valfi/Solenoid Devresi',
  P0450: 'Buhar Emisyon Sistemi Basınç Sensörü Arızası',
  P0457: 'Buhar Emisyon Sistemi Sızıntı Tespiti (Yakıt Kapağı Gevşek/Eksik)',
  P0508: 'Rölanti Hava Kontrol Sistemi Devresi Düşük',
  P0509: 'Rölanti Hava Kontrol Sistemi Devresi Yüksek',
  P0511: 'Rölanti Hava Kontrol Devresi',
  P0524: 'Motor Yağ Basıncı Çok Düşük',
  P0532: 'A/C Soğutucu Basınç Sensörü Devresi Düşük',
  P0533: 'A/C Soğutucu Basınç Sensörü Devresi Yüksek',
  P0572: 'Fren Anahtarı A Devresi Düşük',
  P0573: 'Fren Anahtarı A Devresi Yüksek',
  P0608: 'Kontrol Modülü VSS Çıkışı "A" Arızası',
  P0609: 'Kontrol Modülü VSS Çıkışı "B" Arızası',
  P0630: 'VIN Programlanmamış veya Uyumsuz - ECM/PCM',
  P0634: 'PCM/ECM/TCM Dahili Sıcaklığı Çok Yüksek',
  P0638: 'Gaz Kelebeği Aktüatörü Kontrol Aralığı/Performansı (Banka 1)',
  P0639: 'Gaz Kelebeği Aktüatörü Kontrol Aralığı/Performansı (Banka 2)',
  P0709: 'Vites Aralık Sensörü Devresi Kesintili',
  P0726: 'Motor Devri Giriş Devresi Aralığı/Performansı',
  P0727: 'Motor Devri Giriş Devresi Sinyali Yok',
  P0728: 'Motor Devri Giriş Devresi Kesintili',
  P0840: 'Şanzıman Akışkan Basınç Sensörü/Anahtarı A Devresi',
  P0841: 'Şanzıman Akışkan Basınç Sensörü/Anahtarı A Aralık/Performans',
  P0842: 'Şanzıman Akışkan Basınç Sensörü/Anahtarı A Düşük',
  P0843: 'Şanzıman Akışkan Basınç Sensörü/Anahtarı A Yüksek',
  P0844: 'Şanzıman Akışkan Basınç Sensörü/Anahtarı A Kesintili',
  P0845: 'Şanzıman Akışkan Basınç Sensörü/Anahtarı B Devresi',
  P0900: 'Debriyaj Aktüatörü Devresi / Açık',
  P0901: 'Debriyaj Aktüatörü Devresi Aralık/Performans',
  P0902: 'Debriyaj Aktüatörü Devresi Düşük',
  P0903: 'Debriyaj Aktüatörü Devresi Yüksek',
  P0960: 'Basınç Kontrol Solenoid A Kontrol Devresi Açık',
  P0961: 'Basınç Kontrol Solenoid A Kontrol Devresi Aralık/Performans',
  P0962: 'Basınç Kontrol Solenoid A Kontrol Devresi Düşük',
  P0963: 'Basınç Kontrol Solenoid A Kontrol Devresi Yüksek',
  B0001: 'Sürücü Ön Kademe 1 Açılma Kontrolü Arızası',
  B0002: 'Sürücü Ön Kademe 2 Açılma Kontrolü Arızası',
  B0003: 'Sürücü Ön Kademe 3 Açılma Kontrolü Arızası',
  B0004: 'Sürücü Diz Açılma Kontrolü Arızası',
  B0005: 'Koltuk Sınırlayıcı Açılma Kontrolü Arızası',
  B0014: 'Sürücü Yan Hava Yastığı Açılma Kontrolü Devresi',
  B0015: 'Yolcu Yan Hava Yastığı Açılma Kontrolü Devresi',
  C0034: 'Sağ Ön Teker Hız Sensörü',
  C003A: 'Sağ Arka Teker Hız Sensörü',
  C0043: 'Fren Hidrolik Basıncı C',
  C0044: 'Fren Hidrolik Basıncı D',
  C0047: 'ABS Pompa Rölesi Devresi',
  C0048: 'ABS Pompa Motor Sensörü Devresi',
  C0052: 'Direksiyon Açı Sensörü Devresi',
  C0061: 'Yanal İvme Sensörü Devresi',
  C0062: 'Uzunlamasına İvme Sensörü Devresi',
  C0063: 'Yaw Rate Sensörü Devresi',
  C0064: 'Roll Rate Sensörü Devresi',
  C0081: 'Fren Anahtarı C Devresi',
  U0004: 'Yüksek Hızlı CAN İletişim Bus + Açık',
  U0005: 'Yüksek Hızlı CAN İletişim Bus + Yüksek',
  U0006: 'Yüksek Hızlı CAN İletişim Bus + Düşük',
  U0007: 'Yüksek Hızlı CAN İletişim Bus - Kapalı',
  U0008: 'Yüksek Hızlı CAN İletişim Bus - Açık',
  U0009: 'Yüksek Hızlı CAN İletişim Bus - Yüksek',
  U0011: 'Orta Hız CAN İletişim Bus Performans',
  U0012: 'Orta Hız CAN İletişim Bus + Kapalı',
  U0021: 'Düşük Hız CAN İletişim Bus Performans',
  U0022: 'Düşük Hız CAN İletişim Bus + Kapalı',

};

export function getDTCCategory(code: string): string {
  const prefix = code.charAt(0);
  switch (prefix) {
    case 'P':
      return 'Güç Aktarma (Powertrain)';
    case 'C':
      return 'Şasi (Chassis)';
    case 'B':
      return 'Gövde (Body)';
    case 'U':
      return 'İletişim (Network)';
    default:
      return 'Bilinmeyen';
  }
}

export function getDTCCategoryColor(code: string): string {
  const prefix = code.charAt(0);
  switch (prefix) {
    case 'P':
      return '#ff4757';
    case 'U':
      return '#ff6348';
    case 'C':
      return '#ffa502';
    case 'B':
      return '#ff9ff3';
    default:
      return '#ff4757';
  }
}

export function getDTCSubCategory(code: string): string {
  const match = code.match(/[PCBU](\d{3})/);
  if (!match) {
    return 'Genel';
  }
  const num = parseInt(match[1], 10);
  if (num >= 0 && num < 100) {
    return 'Standart Kodlar';
  }
  if (num >= 100 && num < 200) {
    return 'Yakıt ve Hava Beslemesi';
  }
  if (num >= 200 && num < 300) {
    return 'Yakıt ve Hava Beslemesi (Enjektör)';
  }
  if (num >= 300 && num < 400) {
    return 'Ateşleme Sistemi';
  }
  if (num >= 400 && num < 500) {
    return 'Emisyon Kontrolü';
  }
  if (num >= 500 && num < 600) {
    return 'Hız/Rölanti Kontrolü';
  }
  if (num >= 600 && num < 700) {
    return 'Kontrol Modülü';
  }
  if (num >= 700 && num < 800) {
    return 'Şanzıman';
  }
  if (num >= 800 && num < 900) {
    return 'Şanzıman (İleri)';
  }
  if (num >= 900 && num < 1000) {
    return 'Şanzıman (Diğer)';
  }
  if (num >= 2000 && num < 3000) {
    return 'İleri Diagnostik';
  }
  return 'Diğer';
}

export interface AimechanicAdvice {
  cause: string;
  advice: string;
}

export const DTC_AI_ADVICE: Record<string, AimechanicAdvice> = {
  P0171: {
    cause:
      'Sistem Çok Fakir. Motor yeterince yakıt alamıyor veya fazla hava alıyor.',
    advice:
      '1. MAF sensörünü temizleyin. 2. Emme manifoldunda veya vakum hortumlarında kaçak olup olmadığını kontrol edin. 3. Yakıt filtresi veya pompası yetersiz basınç veriyor olabilir.',
  },
  P0300: {
    cause: 'Rastgele veya Birden Fazla Silindirde Tekleme.',
    advice:
      '1. Buji ve buji kablolarını (veya bobinleri) kontrol edin. 2. Yakıt enjektörlerinde tıkanıklık olabilir. 3. EGR valfi sızıntı yapıyor olabilir.',
  },
  P0420: {
    cause: 'Katalitik Konvertör Verimliliği Düşük.',
    advice:
      '1. Egzoz sızıntısı olup olmadığını kontrol edin. 2. Arka Oksijen (O2) sensörü arızalı olabilir. 3. En kötü senaryoda katalitik konvertör ömrünü tamamlamış veya tıkanmış olabilir.',
  },
  P0102: {
    cause: 'MAF (Kütle Hava Akışı) Sensörü Düşük Voltaj.',
    advice:
      '1. Hava filtresinin tıkalı olup olmadığını kontrol edin. 2. MAF sensörünün fişini ve kablolarını kontrol edin. 3. Sensörü özel MAF temizleyici ile temizlemeyi deneyin.',
  },
  P0455: {
    cause: 'Evap Sisteminde Büyük Kaçak.',
    advice:
      '1. Benzin kapağının gevşek veya contasının yırtık olup olmadığına bakın (En yaygın sebep!). 2. Karbon kanister hortumlarını kontrol edin.',
  },
};
