export type Manufacturer =
  | 'unknown'
  | 'universal'
  | 'vag'
  | 'ford'
  | 'bmw'
  | 'mercedes'
  | 'renault'
  | 'opel'
  | 'peugeot'
  | 'fiat'
  | 'toyota'
  | 'hyundai';

export type HiddenFeature = {
  id: string;
  name: string;
  description: string;
  category: string;
  manufacturer: Manufacturer[];
  compatibility: string;
  readCmd: string;
  readHeader: string;
  writeOn: string;
  writeOff: string;
  writeHeader: string;
};

export const MANUFACTURER_NAMES: Record<Manufacturer, string> = {
  unknown: 'Tanımlanamadı',
  universal: 'Tüm Araçlar',
  vag: 'VAG (VW / Audi / Seat / Skoda)',
  ford: 'Ford',
  bmw: 'BMW / Mini',
  mercedes: 'Mercedes-Benz',
  renault: 'Renault',
  opel: 'Opel / Vauxhall',
  peugeot: 'Peugeot / Citroen / DS',
  fiat: 'Fiat / Alfa / Lancia',
  toyota: 'Toyota / Lexus',
  hyundai: 'Hyundai / Kia',
};

const WMI_LISTS: Record<Manufacturer, string[]> = {
  unknown: [],
  universal: [],
  vag: [
    'WVW',
    'WV1',
    'WV2',
    'WAU',
    'VSS',
    'TMB',
    'TMS',
    '1VW',
    '2VW',
    '3VW',
    'XW8',
  ],
  ford: ['1FA', '1FB', '1FT', 'WF0', 'WF1', 'MAJ', 'VS6'],
  bmw: ['WBA', 'WBS', 'WBY', '5UX', '5YM', 'WMW'],
  mercedes: ['WDB', 'WDC', 'WDD', 'W1K', 'W1N', 'W1V', '4JG'],
  renault: ['VF1', 'VF2', 'VF3', 'VF4', 'VF5', 'VF6', 'VF7', 'VF8'],
  opel: ['W0L', 'W0V', 'S0L'],
  peugeot: ['VF3', 'VF7', 'VR3', 'VR7'],
  fiat: ['ZFA', 'ZFB', 'ZFC', 'ZLA', 'ZAR'],
  toyota: ['JTD', 'JT1', 'JT2', 'JTE', 'JTM', 'SB1'],
  hyundai: ['KMF', 'KMH', 'KNA', 'KNB', 'KNC', 'TMA', 'TMB'],
};

export function detectManufacturer(vin: string): Manufacturer {
  const wmi = vin.substring(0, 3).toUpperCase();
  const wmi2 = vin.substring(0, 2).toUpperCase();
  for (const [mfr, prefixes] of Object.entries(WMI_LISTS)) {
    if (mfr === 'universal') {
      continue;
    }
    if (prefixes.some(p => wmi.startsWith(p) || wmi2.startsWith(p))) {
      return mfr as Manufacturer;
    }
  }
  if (wmi !== '' && wmi !== 'XXX') {
    return 'universal';
  }
  return 'universal';
}

export const ALL_FEATURES: HiddenFeature[] = [
  // ─── DPF (Dizel Partikül Filtresi) ───
  {
    id: 'dpf_soot_mass',
    name: 'DPF Kurum Doluluk',
    description: 'Dizel partikül filtresindeki kurum miktarını oku (gram)',
    category: 'DPF',
    manufacturer: ['universal'],
    compatibility: "DPF'li dizel araçlar (2008+)",
    readCmd: '22F900',
    readHeader: '7E0',
    writeOn: '',
    writeOff: '',
    writeHeader: '7E0',
  },
  {
    id: 'dpf_ash_mass',
    name: 'DPF Kül Doluluk',
    description: "DPF'de biriken kül miktarı (gram)",
    category: 'DPF',
    manufacturer: ['universal'],
    compatibility: "DPF'li dizel araçlar",
    readCmd: '22F901',
    readHeader: '7E0',
    writeOn: '',
    writeOff: '',
    writeHeader: '7E0',
  },
  {
    id: 'dpf_pressure',
    name: 'DPF Fark Basıncı',
    description: 'DPF giriş-çıkış arası basınç farkı (mbar)',
    category: 'DPF',
    manufacturer: ['universal'],
    compatibility: 'DPF basınç sensörlü araçlar',
    readCmd: '22F902',
    readHeader: '7E0',
    writeOn: '',
    writeOff: '',
    writeHeader: '7E0',
  },
  {
    id: 'dpf_temp_in',
    name: 'DPF Giriş Sıcaklığı',
    description: 'DPF öncesi egzoz gazı sıcaklığı',
    category: 'DPF',
    manufacturer: ['universal'],
    compatibility: "DPF'li dizel araçlar",
    readCmd: '22F903',
    readHeader: '7E0',
    writeOn: '',
    writeOff: '',
    writeHeader: '7E0',
  },
  {
    id: 'dpf_temp_out',
    name: 'DPF Çıkış Sıcaklığı',
    description: 'DPF sonrası egzoz gazı sıcaklığı',
    category: 'DPF',
    manufacturer: ['universal'],
    compatibility: "DPF'li dizel araçlar",
    readCmd: '22F904',
    readHeader: '7E0',
    writeOn: '',
    writeOff: '',
    writeHeader: '7E0',
  },
  {
    id: 'dpf_distance_since_reg',
    name: 'Son Rejenerasyon Mesafesi',
    description: 'Son DPF rejenerasyonundan beri km',
    category: 'DPF',
    manufacturer: ['universal'],
    compatibility: "DPF'li dizel araçlar",
    readCmd: '22F905',
    readHeader: '7E0',
    writeOn: '',
    writeOff: '',
    writeHeader: '7E0',
  },
  {
    id: 'dpf_reg_status',
    name: 'DPF Rejenerasyon Durumu',
    description: 'DPF rejenerasyonunun aktif/pasif durumu',
    category: 'DPF',
    manufacturer: ['universal'],
    compatibility: "DPF'li dizel araçlar",
    readCmd: '22F906',
    readHeader: '7E0',
    writeOn: '',
    writeOff: '',
    writeHeader: '7E0',
  },
  {
    id: 'dpf_volumetric_load',
    name: 'DPF Hacimsel Doluluk',
    description: 'DPF doluluk yüzdesi (hacimsel)',
    category: 'DPF',
    manufacturer: ['universal'],
    compatibility: "DPF'li dizel araçlar",
    readCmd: '22F907',
    readHeader: '7E0',
    writeOn: '',
    writeOff: '',
    writeHeader: '7E0',
  },

  // ─── BOĞAZ KALİBRASYONU (Throttle) ───
  {
    id: 'throttle_adaptation',
    name: 'Gaz Kelebeği Adaptasyonu',
    description: 'Gaz kelebeği sıfırlama ve yeniden öğrenme (TPS adaptasyon)',
    category: 'Kalibrasyon',
    manufacturer: ['universal'],
    compatibility: 'Elektronik gaz kelebeğine sahip araçlar',
    readCmd: '22F910',
    readHeader: '7E0',
    writeOn: '31F9100303',
    writeOff: '',
    writeHeader: '7E0',
  },
  {
    id: 'throttle_position_learn',
    name: 'Gaz Kelebeği Pozisyon Öğrenme',
    description: 'Kelebek açısı sıfır ve tam açık pozisyonlarını öğret',
    category: 'Kalibrasyon',
    manufacturer: ['universal'],
    compatibility: 'Drive-by-wire araçlar',
    readCmd: '22F911',
    readHeader: '7E0',
    writeOn: '31F9110303',
    writeOff: '',
    writeHeader: '7E0',
  },
  {
    id: 'throttle_reset_adaption',
    name: 'Adaptasyon Değerlerini Sıfırla',
    description: 'ECU adaptasyon değerlerini fabrika ayarlarına döndür',
    category: 'Kalibrasyon',
    manufacturer: ['universal'],
    compatibility: 'Elektronik gaz kelebeğine sahip araçlar',
    readCmd: '22F912',
    readHeader: '7E0',
    writeOn: '31F9120303',
    writeOff: '',
    writeHeader: '7E0',
  },
  {
    id: 'idle_speed_learn',
    name: 'Rölanti Devri Öğrenme',
    description: 'Rölanti hava kontrolünü yeniden kalibre et',
    category: 'Kalibrasyon',
    manufacturer: ['universal'],
    compatibility: 'Elektronik gaz kelebeğine sahip araçlar',
    readCmd: '22F913',
    readHeader: '7E0',
    writeOn: '31F9130303',
    writeOff: '',
    writeHeader: '7E0',
  },
  {
    id: 'accelerator_pedal_cal',
    name: 'Gaz Pedalı Kalibrasyonu',
    description: 'Gaz pedalı konum sensörünü kalibre et',
    category: 'Kalibrasyon',
    manufacturer: ['universal'],
    compatibility: 'Elektronik gaz pedalına sahip araçlar',
    readCmd: '22F914',
    readHeader: '7E0',
    writeOn: '31F9140303',
    writeOff: '',
    writeHeader: '7E0',
  },

  // ─── SERVIS SIFIRLAMA ───
  {
    id: 'service_reset_oil',
    name: 'Yağ Servisi Sıfırlama',
    description: 'Yağ değişim uyarısını sıfırla (service light)',
    category: 'Servis',
    manufacturer: ['universal'],
    compatibility: 'UDS destekli araçlar (2010+)',
    readCmd: '22F920',
    readHeader: '7E0',
    writeOn: '31F9200303',
    writeOff: '',
    writeHeader: '7E0',
  },
  {
    id: 'service_reset_inspection',
    name: 'Bakım Uyarısı Sıfırlama',
    description: 'Periyodik bakım uyarısını sıfırla (inspection light)',
    category: 'Servis',
    manufacturer: ['universal'],
    compatibility: 'UDS destekli araçlar (2010+)',
    readCmd: '22F921',
    readHeader: '7E0',
    writeOn: '31F9210303',
    writeOff: '',
    writeHeader: '7E0',
  },
  {
    id: 'service_reset_vag',
    name: 'VAG Servis Sıfırlama',
    description: 'VAG grubu araçlarda yağ/bakım uyarılarını sıfırla',
    category: 'Servis',
    manufacturer: ['vag'],
    compatibility: 'VW Golf 5+, Audi A3 8P+, Seat Leon 2+, Skoda Octavia 2+',
    readCmd: '22F922',
    readHeader: '7E0',
    writeOn: '31F9220303',
    writeOff: '',
    writeHeader: '7E0',
  },
  {
    id: 'service_reset_bmw',
    name: 'BMW CBS Servis Sıfırlama',
    description: 'BMW Condition Based Servis uyarılarını sıfırla',
    category: 'Servis',
    manufacturer: ['bmw'],
    compatibility: 'BMW E90+, F20+, Mini R56+',
    readCmd: '22F923',
    readHeader: '7E0',
    writeOn: '31F9230303',
    writeOff: '',
    writeHeader: '7E0',
  },
  {
    id: 'service_reset_ford',
    name: 'Ford Servis Sıfırlama',
    description: 'Ford araçlarda yağ değişim uyarısını sıfırla',
    category: 'Servis',
    manufacturer: ['ford'],
    compatibility: 'Ford Focus 2+, Mondeo 4+, Kuga 1+',
    readCmd: '22F924',
    readHeader: '7E0',
    writeOn: '31F9240303',
    writeOff: '',
    writeHeader: '7E0',
  },
  {
    id: 'service_reset_mercedes',
    name: 'Mercedes Servis Sıfırlama',
    description: 'Mercedes araçlarda servis uyarısını sıfırla (ASSYST)',
    category: 'Servis',
    manufacturer: ['mercedes'],
    compatibility: 'Mercedes W204+, W212+, C180+',
    readCmd: '22F925',
    readHeader: '7E0',
    writeOn: '31F9250303',
    writeOff: '',
    writeHeader: '7E0',
  },
  {
    id: 'service_reset_toyota',
    name: 'Toyota Servis Sıfırlama',
    description: 'Toyota/Lexus araçlarda bakım uyarısını sıfırla',
    category: 'Servis',
    manufacturer: ['toyota'],
    compatibility: 'Toyota Corolla 10+, Auris 2+, Avensis 3+',
    readCmd: '22F926',
    readHeader: '7E0',
    writeOn: '31F9260303',
    writeOff: '',
    writeHeader: '7E0',
  },
  {
    id: 'service_reset_hyundai',
    name: 'Hyundai Servis Sıfırlama',
    description: 'Hyundai/Kia araçlarda bakım uyarısını sıfırla',
    category: 'Servis',
    manufacturer: ['hyundai'],
    compatibility: 'Hyundai i30+, Tucson+, Kia Ceed+',
    readCmd: '22F927',
    readHeader: '7E0',
    writeOn: '31F9270303',
    writeOff: '',
    writeHeader: '7E0',
  },

  // ─── EK DIAGNOSTIK ───
  {
    id: 'diag_extended_session',
    name: 'Genişletilmiş Oturum',
    description:
      'ECU genişletilmiş diagnostik oturumuna geç (kodlama/servis için)',
    category: 'Diagnostik',
    manufacturer: ['universal'],
    compatibility: 'UDS destekli tüm araçlar',
    readCmd: '1003',
    readHeader: '7E0',
    writeOn: '',
    writeOff: '',
    writeHeader: '7E0',
  },
  {
    id: 'diag_programming_session',
    name: 'Programlama Oturumu',
    description: 'ECU programlama oturumuna geç',
    category: 'Diagnostik',
    manufacturer: ['universal'],
    compatibility: 'UDS destekli tüm araçlar',
    readCmd: '1002',
    readHeader: '7E0',
    writeOn: '',
    writeOff: '',
    writeHeader: '7E0',
  },
  {
    id: 'diag_tester_present',
    name: 'TesterPresent Gönder',
    description: 'ECU bağlantısını canlı tut (3sn aralıkla)',
    category: 'Diagnostik',
    manufacturer: ['universal'],
    compatibility: 'UDS destekli tüm araçlar',
    readCmd: '3E00',
    readHeader: '7E0',
    writeOn: '',
    writeOff: '',
    writeHeader: '7E0',
  },
  {
    id: 'diag_vin_uds',
    name: 'VIN Oku (UDS)',
    description: 'UDS protokolü ile VIN sorgula',
    category: 'Diagnostik',
    manufacturer: ['universal'],
    compatibility: 'UDS destekli tüm araçlar',
    readCmd: '22F190',
    readHeader: '7E0',
    writeOn: '',
    writeOff: '',
    writeHeader: '7E0',
  },

  // ─── GİZLİ ÖZELLİKLER (KODLAMA) ───
  {
    id: 'vag_needle_sweep',
    name: 'Kadran Selamlama',
    description:
      'Kontak açıldığında ibrelerin sona vurup dönmesi (Needle Sweep)',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['vag'],
    compatibility: 'VW Golf, Seat Leon, Skoda Octavia (Gösterge Paneli)',
    readCmd: '221701',
    readHeader: '714',
    writeOn: '2E170101',
    writeOff: '2E170100',
    writeHeader: '714',
  },
  {
    id: 'vag_seatbelt_warning',
    name: 'Emniyet Kemeri Uyarısı İptali',
    description: 'Gösterge panelindeki emniyet kemeri uyarı sesini kapatır',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['vag'],
    compatibility: 'VAG Grubu (Gösterge Paneli)',
    readCmd: '221702',
    readHeader: '714',
    writeOn: '2E170200',
    writeOff: '2E170201',
    writeHeader: '714',
  },
  {
    id: 'vag_mirror_dip',
    name: 'Geri Viteste Ayna İnmesi',
    description:
      'Geri vitese takıldığında sağ aynanın aşağıyı göstermesini sağlar (Mirror Dip)',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['vag'],
    compatibility: 'VAG Grubu (Kapı Modülü - 52)',
    readCmd: '225201',
    readHeader: '752',
    writeOn: '2E520101',
    writeOff: '2E520100',
    writeHeader: '752',
  },
  {
    id: 'vag_offroad_display',
    name: 'Off-Road Bilgi Ekranı',
    description: 'Teyp menüsüne Off-Road ekranını ekler (Açı, pusula, vs.)',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['vag'],
    compatibility: 'Discover Media / Pro (5F Modülü)',
    readCmd: '225F01',
    readHeader: '75F',
    writeOn: '2E5F0101',
    writeOff: '2E5F0100',
    writeHeader: '75F',
  },
  {
    id: 'bmw_start_stop_mem',
    name: 'Start/Stop Hafızası',
    description: 'Aracı yeniden çalıştırdığınızda Start/Stop ayarını hatırlar',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['bmw'],
    compatibility: 'BMW F ve G Serisi (BDC/FEM)',
    readCmd: '222001',
    readHeader: '700',
    writeOn: '2E200101',
    writeOff: '2E200100',
    writeHeader: '700',
  },
  {
    id: 'bmw_digital_speedo',
    name: 'Dijital Hız Göstergesi',
    description: 'Yol bilgisayarında anlık dijital hız gösterimini aktif eder',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['bmw'],
    compatibility: 'BMW E90, F20, F30 (Kombi)',
    readCmd: '222002',
    readHeader: '700',
    writeOn: '2E200201',
    writeOff: '2E200200',
    writeHeader: '700',
  },
  {
    id: 'bmw_video_in_motion',
    name: 'Hareket Halinde Video',
    description:
      'Araç hareket halindeyken iDrive üzerinden video izlemeyi aktif eder',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['bmw'],
    compatibility: 'BMW NBT / NBT EVO / MGU',
    readCmd: '226301',
    readHeader: '763',
    writeOn: '2E630101',
    writeOff: '2E630100',
    writeHeader: '763',
  },
  {
    id: 'ford_auto_lock',
    name: 'Otomatik Kapı Kilitleme',
    description: 'Araç 15 km/s hızı geçince kapıları otomatik kilitler',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['ford'],
    compatibility: 'Ford Focus, Fiesta, Mondeo (BCM)',
    readCmd: '223001',
    readHeader: '726',
    writeOn: '2E300101',
    writeOff: '2E300100',
    writeHeader: '726',
  },
  {
    id: 'ford_cornering_fog',
    name: 'Viraj Aydınlatması',
    description:
      'Sinyal verildiğinde veya direksiyon çevrildiğinde sis farı yanar',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['ford', 'vag', 'renault'],
    compatibility: 'BCM Destekli Araçlar',
    readCmd: '223002',
    readHeader: '726',
    writeOn: '2E300201',
    writeOff: '2E300200',
    writeHeader: '726',
  },
  {
    id: 'ford_global_windows',
    name: 'Kumandadan Cam Kontrolü',
    description:
      'Kumandanın açma/kilitleme tuşuna basılı tutarak tüm camları kontrol etme',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['ford'],
    compatibility: 'Ford Focus, Mondeo, Kuga',
    readCmd: '223004',
    readHeader: '726',
    writeOn: '2E300401',
    writeOff: '2E300400',
    writeHeader: '726',
  },
  {
    id: 'renault_rs_monitor',
    name: 'R.S. Monitor Aktifleştirme',
    description: 'R-Link ekranında spor RS Monitor uygulamasını açar',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['renault'],
    compatibility: 'Renault Megane 4, Clio 4 (R-Link)',
    readCmd: '224001',
    readHeader: '7A0',
    writeOn: '2E400101',
    writeOff: '2E400100',
    writeHeader: '7A0',
  },
  {
    id: 'renault_fatigue_warning',
    name: 'Yorgunluk Algılayıcı (Fatigue)',
    description: 'Yorgunluk uyarı sistemini gösterge panelinde aktif eder',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['renault'],
    compatibility: 'Renault Megane 4, Kadjar, Talisman',
    readCmd: '224002',
    readHeader: '7A0',
    writeOn: '2E400201',
    writeOff: '2E400200',
    writeHeader: '7A0',
  },
  {
    id: 'opel_opc_theme',
    name: 'OPC Ekran Teması',
    description: 'Gösterge ekranında OPC spor temasını aktifleştirir',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['opel'],
    compatibility: 'Opel Astra K, Insignia',
    readCmd: '225001',
    readHeader: '760',
    writeOn: '2E500101',
    writeOff: '2E500100',
    writeHeader: '760',
  },
  {
    id: 'mercedes_amg_logo',
    name: 'AMG Karşılama Logosu',
    description: 'Teyp açılışında AMG logosunu gösterir',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['mercedes'],
    compatibility: 'Mercedes Audio 20 / COMAND',
    readCmd: '226001',
    readHeader: '7E0',
    writeOn: '2E600101',
    writeOff: '2E600100',
    writeHeader: '7E0',
  },
  {
    id: 'fiat_seatbelt_chime',
    name: 'Emniyet Kemeri Ses İptali',
    description: 'Fiat araçlarda kemer ikaz sesini kapatır',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['fiat'],
    compatibility: 'Fiat Egea / Tipo / Punto',
    readCmd: '227001',
    readHeader: '732',
    writeOn: '2E700100',
    writeOff: '2E700101',
    writeHeader: '732',
  },
  {
    id: 'toyota_window_remote',
    name: 'Kumandadan Cam İndirme',
    description: 'Kumandadaki açma tuşuna basılı tutunca tüm camlar iner',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['toyota'],
    compatibility: 'Toyota Corolla, C-HR (BCM)',
    readCmd: '228001',
    readHeader: '750',
    writeOn: '2E800101',
    writeOff: '2E800100',
    writeHeader: '750',
  },
  {
    id: 'bmw_seatbelt_chime',
    name: 'BMW Kemer İkaz İptali',
    description:
      'BMW araçlarda emniyet kemeri sesini (Gong) kalıcı olarak susturur.',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['bmw'],
    compatibility: 'BMW F ve G Serisi',
    readCmd: '222003',
    readHeader: '700',
    writeOn: '2E200300',
    writeOff: '2E200301',
    writeHeader: '700',
  },
  {
    id: 'ford_st_logo',
    name: 'Ford ST/RS Ekran Logosu',
    description:
      'SYNC ekranında veya kadranda açılışta ST/RS logosunu gösterir.',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['ford'],
    compatibility: 'Ford Focus 3/4, Fiesta MK8',
    readCmd: '223003',
    readHeader: '726',
    writeOn: '2E300301',
    writeOff: '2E300300',
    writeHeader: '726',
  },
  {
    id: 'vag_acoustic_lock',
    name: 'Kilit Onay Sesi (Korona)',
    description: 'Aracı kilitlerken ve açarken kornadan bip sesi gelir',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['vag'],
    compatibility: 'VAG Grubu (BCM - 09)',
    readCmd: '220901',
    readHeader: '709',
    writeOn: '2E090101',
    writeOff: '2E090100',
    writeHeader: '709',
  },
  {
    id: 'vag_refuel_quantity',
    name: 'Ek Yakıt Bilgisi',
    description: 'Deponun dolması için gereken yakıt miktarını litre olarak gösterir',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['vag'],
    compatibility: 'VAG Grubu (Gösterge Paneli - 17)',
    readCmd: '221703',
    readHeader: '714',
    writeOn: '2E170301',
    writeOff: '2E170300',
    writeHeader: '714',
  },
  {
    id: 'vag_us_sidemarkers',
    name: 'Amerikan Park Sinyaller',
    description: 'Ön sinyal lambalarının parklar ile birlikte %30 kısık yanması',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['vag'],
    compatibility: 'VAG Grubu (BCM - 09)',
    readCmd: '220902',
    readHeader: '709',
    writeOn: '2E090230',
    writeOff: '2E090200',
    writeHeader: '709',
  },
  {
    id: 'bmw_tpms_temp',
    name: 'Lastik Basınç ve Sıcaklık',
    description: 'iDrive ekranında lastik basıncına ek olarak sıcaklık değerlerini gösterir',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['bmw'],
    compatibility: 'BMW F ve G Serisi (HU_NBT/HU_MGU)',
    readCmd: '226302',
    readHeader: '763',
    writeOn: '2E630201',
    writeOff: '2E630200',
    writeHeader: '763',
  },
  {
    id: 'bmw_rear_drl',
    name: 'Arka Stoplar Gündüz Farı',
    description: 'Gündüz farları (DRL) yanarken arka stopların da yanmasını sağlar',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['bmw'],
    compatibility: 'BMW F ve G Serisi (BDC/REM)',
    readCmd: '222004',
    readHeader: '700',
    writeOn: '2E200401',
    writeOff: '2E200400',
    writeHeader: '700',
  },
  {
    id: 'renault_tpms_disable',
    name: 'TPMS (Lastik Basınç) Kapatma',
    description: 'Lastik basınç sensörü uyarısını gösterge panelinden tamamen kapatır',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['renault'],
    compatibility: 'Renault Megane 3/4, Clio 4/5',
    readCmd: '224003',
    readHeader: '7A0',
    writeOn: '2E400300',
    writeOff: '2E400301',
    writeHeader: '7A0',
  },
  {
    id: 'opel_advanced_trip',
    name: 'Gelişmiş Yol Bilgisayarı',
    description: 'Göstergedeki ek sekmeleri açar (Akü voltajı, soğutma suyu, eko trend)',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['opel'],
    compatibility: 'Opel Astra J/K, Insignia A/B',
    readCmd: '225002',
    readHeader: '760',
    writeOn: '2E500201',
    writeOff: '2E500200',
    writeHeader: '760',
  },
  {
    id: 'vag_coming_home',
    name: 'Coming / Leaving Home (Far Gecikmesi)',
    description: 'Aracı kilitlediğinizde veya açtığınızda farların belirli bir süre yanık kalması',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['vag'],
    compatibility: 'VAG Grubu (BCM - 09)',
    readCmd: '220903',
    readHeader: '709',
    writeOn: '2E090301',
    writeOff: '2E090300',
    writeHeader: '709',
  },
  {
    id: 'vag_start_stop_disable',
    name: 'Start/Stop İptali',
    description: 'Voltaj limitini değiştirerek Start/Stop sistemini kalıcı olarak devre dışı bırakır',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['vag'],
    compatibility: 'VAG Grubu (Gateway - 19)',
    readCmd: '221901',
    readHeader: '719',
    writeOn: '2E190112', // 12.1V limit for disable
    writeOff: '2E190107', // 7.6V limit for enable
    writeHeader: '719',
  },
  {
    id: 'vag_oil_temp',
    name: 'Yol Bilgisayarı Yağ Sıcaklığı',
    description: 'Yol bilgisayarı (MFA) ekranına anlık yağ sıcaklığı göstergesini ekler',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['vag'],
    compatibility: 'VAG Grubu (Gösterge - 17)',
    readCmd: '221704',
    readHeader: '714',
    writeOn: '2E170401',
    writeOff: '2E170400',
    writeHeader: '714',
  },
  {
    id: 'bmw_sport_displays',
    name: 'Spor Göstergeler (Sport Displays)',
    description: 'iDrive ekranında anlık beygir ve tork gösteren spor ekranları aktif eder',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['bmw'],
    compatibility: 'BMW F ve G Serisi (HU_NBT)',
    readCmd: '226303',
    readHeader: '763',
    writeOn: '2E630301',
    writeOff: '2E630300',
    writeHeader: '763',
  },
  {
    id: 'bmw_m_startup',
    name: 'M Performance Açılış Logosu',
    description: 'NBT ve Kadranda açılışta BMW logosu yerine M logosunu gösterir',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['bmw'],
    compatibility: 'BMW F Serisi (Kombi/NBT)',
    readCmd: '222005',
    readHeader: '700',
    writeOn: '2E200501',
    writeOff: '2E200500',
    writeHeader: '700',
  },
  {
    id: 'ford_auto_lock_speed',
    name: 'Otomatik Kilitlenme Hız Ayarı',
    description: 'Kapıların otomatik kilitlenme hızını 20 km/s olarak ayarlar',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['ford'],
    compatibility: 'Ford BCM Modülleri',
    readCmd: '223005',
    readHeader: '726',
    writeOn: '2E300514', // 20 hex is 14
    writeOff: '2E300507', // 7 hex (default)
    writeHeader: '726',
  },
  {
    id: 'renault_cornering_fog',
    name: 'Dönüşe Duyarlı Sis Farları',
    description: 'Direksiyon çevrildiğinde ilgili sis farının yanmasını sağlar',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['renault'],
    compatibility: 'Renault Megane 4, Talisman',
    readCmd: '224004',
    readHeader: '7A0',
    writeOn: '2E400401',
    writeOff: '2E400400',
    writeHeader: '7A0',
  },
  {
    id: 'mercedes_seatbelt_chime',
    name: 'Emniyet Kemeri Ses İptali',
    description: 'Mercedes araçlarda kemer ikaz sesini kapatır',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['mercedes'],
    compatibility: 'Mercedes W204, W212, C117',
    readCmd: '226002',
    readHeader: '7E0',
    writeOn: '2E600200',
    writeOff: '2E600201',
    writeHeader: '7E0',
  },
  {
    id: 'peugeot_theme_red',
    name: 'Spor Kırmızı Tema (SMEG)',
    description: 'SMEG teyp ekranında gizli spor kırmızı temayı aktif eder',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['peugeot'],
    compatibility: 'Peugeot 208, 308 (SMEG/SMEG+)',
    readCmd: '22A001',
    readHeader: '7A0',
    writeOn: '2EA00101',
    writeOff: '2EA00100',
    writeHeader: '7A0',
  },
  {
    id: 'toyota_lane_assist',
    name: 'Şerit Takip Hassasiyeti',
    description: 'LTA (Şerit takip) sisteminin direksiyon müdahale hassasiyetini artırır',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['toyota'],
    compatibility: 'Toyota Safety Sense destekli araçlar',
    readCmd: '228002',
    readHeader: '750',
    writeOn: '2E800202', // High sensitivity
    writeOff: '2E800201', // Normal sensitivity
    writeHeader: '750',
  },
  {
    id: 'vag_lap_timer',
    name: 'Tur Zamanlayıcı (Lap Timer)',
    description: 'Gösterge paneli menüsüne kronometre / tur zamanlayıcı ekler',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['vag'],
    compatibility: 'VAG Grubu (Gösterge - 17)',
    readCmd: '221705',
    readHeader: '714',
    writeOn: '2E170501',
    writeOff: '2E170500',
    writeHeader: '714',
  },
  {
    id: 'vag_teardrop_wipe',
    name: 'Gözyaşı Silme (Teardrop Wiping)',
    description: 'Silecekler durduktan 3 saniye sonra camda kalan suyu silmek için 1 kez daha çalışır',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['vag'],
    compatibility: 'VAG Grubu (Silecek Modülü - 09)',
    readCmd: '220904',
    readHeader: '709',
    writeOn: '2E090401',
    writeOff: '2E090400',
    writeHeader: '709',
  },
  {
    id: 'vag_fog_highbeam',
    name: 'Selektörde Sis Farları',
    description: 'Selektör yaptığınızda uzun farlarla birlikte sis farları da çakar',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['vag'],
    compatibility: 'VAG Grubu (BCM - 09)',
    readCmd: '220905',
    readHeader: '709',
    writeOn: '2E090501',
    writeOff: '2E090500',
    writeHeader: '709',
  },
  {
    id: 'bmw_legal_disclaimer',
    name: 'Yasal Uyarı İptali (iDrive)',
    description: 'Her çalıştırmada iDrive ekranında çıkan yasal uyarı metnini kaldırır',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['bmw'],
    compatibility: 'BMW F ve G Serisi (HU_NBT)',
    readCmd: '226304',
    readHeader: '763',
    writeOn: '2E630400',
    writeOff: '2E630401',
    writeHeader: '763',
  },
  {
    id: 'bmw_ac_memory',
    name: 'Klima Hafızası (AC Memory)',
    description: 'Aracı kapattığınızdaki klima ayarını (Açık/Kapalı) sonraki çalıştırmada hatırlar',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['bmw'],
    compatibility: 'BMW F ve G Serisi (IHKA)',
    readCmd: '227801',
    readHeader: '780',
    writeOn: '2E780101',
    writeOff: '2E780100',
    writeHeader: '780',
  },
  {
    id: 'bmw_door_radio_off',
    name: 'Kapı Açılınca Teyp Kapanması',
    description: 'Motoru stop edip şoför kapısını açtığınızda iDrive ve radyo otomatik kapanır',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['bmw'],
    compatibility: 'BMW F ve G Serisi (BDC/FEM)',
    readCmd: '222006',
    readHeader: '700',
    writeOn: '2E200601',
    writeOff: '2E200600',
    writeHeader: '700',
  },
  {
    id: 'ford_bambi_mode',
    name: 'Bambi Modu (Sis + Uzun Far)',
    description: 'Uzun farları yaktığınızda sis farlarının kapanmasını engeller (İkisi de yanar)',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['ford'],
    compatibility: 'Ford Focus, Ranger, F-150',
    readCmd: '223006',
    readHeader: '726',
    writeOn: '2E300601',
    writeOff: '2E300600',
    writeHeader: '726',
  },
  {
    id: 'ford_double_honk',
    name: 'Çift Korna İptali',
    description: 'Araç çalışırken anahtarla dışarı çıkıp kapıyı kapattığınızdaki uyarı kornasını iptal eder',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['ford'],
    compatibility: 'Ford Anahtarsız Çalıştırma (Keyless)',
    readCmd: '223007',
    readHeader: '726',
    writeOn: '2E300700',
    writeOff: '2E300701',
    writeHeader: '726',
  },
  {
    id: 'ford_temp_numbers',
    name: 'Göstergede Hararet Derecesi',
    description: 'Analog motor sıcaklık ibresinin üstünde dijital olarak net dereceyi (C) gösterir',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['ford'],
    compatibility: 'Ford Sync 3 / Dijital Kadran',
    readCmd: '223008',
    readHeader: '720',
    writeOn: '2E300801',
    writeOff: '2E300800',
    writeHeader: '720',
  },
  {
    id: 'renault_carplay_androidauto',
    name: 'Apple CarPlay & Android Auto',
    description: 'R-Link 2 sisteminde gizli olan CarPlay ve Android Auto menülerini aktif eder',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['renault'],
    compatibility: 'Renault Megane 4, Kadjar (R-Link 2 v3.3+)',
    readCmd: '224005',
    readHeader: '7A0',
    writeOn: '2E400501',
    writeOff: '2E400500',
    writeHeader: '7A0',
  },
  {
    id: 'renault_video_in_motion',
    name: 'Hareket Halinde Video İzleme',
    description: 'R-Link ekranında araç giderken video izleme kilidini kaldırır',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['renault'],
    compatibility: 'Renault R-Link 2',
    readCmd: '224006',
    readHeader: '7A0',
    writeOn: '2E400601',
    writeOff: '2E400600',
    writeHeader: '7A0',
  },
  {
    id: 'renault_welcome_anim',
    name: 'GT/RS Açılış Animasyonu',
    description: 'Ekran açılışında Renault logosu yerine GT veya RS Line animasyonu koyar',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['renault'],
    compatibility: 'Renault R-Link 2 / Easy Link',
    readCmd: '224007',
    readHeader: '7A0',
    writeOn: '2E400702', // 02 for GT, 03 for RS
    writeOff: '2E400701', // 01 for standard
    writeHeader: '7A0',
  },
  {
    id: 'fiat_srt_pages',
    name: 'SRT Performance Pages',
    description: 'Uconnect ekranında G-Force, Timer, Motor Verileri gibi SRT ekranlarını açar',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['fiat'], // Fiat Chrysler Automobiles (FCA)
    compatibility: 'Fiat Egea, Jeep, Dodge (Uconnect 7/8.4)',
    readCmd: '227002',
    readHeader: '732',
    writeOn: '2E700201',
    writeOff: '2E700200',
    writeHeader: '732',
  },
  {
    id: 'peugeot_diag_menu',
    name: 'Gizli Diagnostik Menüsü (SMEG)',
    description: 'Teyp üzerinde lastik basınçları ve hata kodlarını gösteren mühendislik menüsü',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['peugeot'],
    compatibility: 'Peugeot / Citroen SMEG Ekran',
    readCmd: '22A002',
    readHeader: '7A0',
    writeOn: '2EA00201',
    writeOff: '2EA00200',
    writeHeader: '7A0',
  },
  {
    id: 'opel_vauxhall_logo',
    name: 'Vauxhall/Buick Logosu',
    description: 'Kadran veya IntelliLink ekranında Opel yerine Vauxhall/Buick logosu gösterimi',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['opel'],
    compatibility: 'Opel Astra, Insignia',
    readCmd: '225003',
    readHeader: '760',
    writeOn: '2E500302',
    writeOff: '2E500301',
    writeHeader: '760',
  },
  {
    id: 'mercedes_max_ac',
    name: 'Klima MAX AC Modu',
    description: 'Sıcak ülkeler için gizlenmiş olan "MAX AC" modunu klima paneline ekler',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['mercedes'],
    compatibility: 'Mercedes W205, W213',
    readCmd: '226003',
    readHeader: '7E0',
    writeOn: '2E600301',
    writeOff: '2E600300',
    writeHeader: '7E0',
  },
  {
    id: 'mercedes_stopwatch',
    name: 'Kronometre (Stopwatch)',
    description: 'Gösterge paneli menüsüne kronometre özelliğini aktif eder',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['mercedes'],
    compatibility: 'Mercedes Gösterge (IC_204)',
    readCmd: '226004',
    readHeader: '7E0',
    writeOn: '2E600401',
    writeOff: '2E600400',
    writeHeader: '7E0',
  },
  {
    id: 'vag_mirror_fold',
    name: 'Kumandadan Otomatik Katlanır Ayna',
    description: 'Araç kilitlendiğinde aynaların otomatik katlanmasını sağlar',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['vag'],
    compatibility: 'VAG Grubu (Kapı Modülü - 42/52)',
    readCmd: '224201',
    readHeader: '742',
    writeOn: '2E420101',
    writeOff: '2E420100',
    writeHeader: '742',
  },
  {
    id: 'bmw_brake_force_display',
    name: 'Acil Frende Çakarlı Stoplar (BFD)',
    description: 'Sert fren yapıldığında arka stop lambalarının hızla çakarak uyarı vermesi',
    category: 'Gizli Özellik (Kodlama)',
    manufacturer: ['bmw'],
    compatibility: 'BMW F ve G Serisi (BDC)',
    readCmd: '222007',
    readHeader: '700',
    writeOn: '2E200701',
    writeOff: '2E200700',
    writeHeader: '700',
  }
];

export function getFeaturesForManufacturer(mfr: Manufacturer): HiddenFeature[] {
  return ALL_FEATURES.filter(
    f => f.manufacturer.includes(mfr) || f.manufacturer.includes('universal'),
  );
}

export function getManufacturerIcon(mfr: Manufacturer): string {
  const icons: Record<Manufacturer, string> = {
    unknown: '❓',
    universal: '🔧',
    vag: '🏎️',
    ford: '🐎',
    bmw: '🌀',
    mercedes: '⭐',
    renault: '💎',
    opel: '⚡',
    peugeot: '🦁',
    fiat: '🔴',
    toyota: '🌐',
    hyundai: '🔷',
  };
  return icons[mfr] || '🔧';
}

export function getAllManufacturers(): Manufacturer[] {
  return [
    'universal',
    'vag',
    'ford',
    'bmw',
    'mercedes',
    'renault',
    'opel',
    'peugeot',
    'fiat',
    'toyota',
    'hyundai',
  ];
}
