org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=512m
org.gradle.java.home=C:/Program Files/Android/Android Studio/jbr
android.useAndroidX=true
android.enableDexingArtifactTransform=false
newArchEnabled=false
hermesEnabled=true
MYAPP_UPLOAD_STORE_FILE=arabanitanistore.jks
MYAPP_UPLOAD_KEY_ALIAS=arabanitani
MYAPP_UPLOAD_STORE_PASSWORD=a159357
MYAPP_UPLOAD_KEY_PASSWORD=a159357
