const fs = require('fs');
const filePath = 'src/services/DTCDatabase.ts';
let content = fs.readFileSync(filePath, 'utf8');

const newDTCs = `
  P0423: 'Katalitik Konvertör Verimi Eşik Altı (Isıtma) (Banka 1)',
  P0424: 'Katalitik Konvertör Sıcaklığı Eşik Altı (Banka 1)',
  P0446: 'Buhar Emisyon Kontrol Sistemi Havalandırma Kontrol Devresi',
  P0447: 'Buhar Emisyon Kontrol Sistemi Havalandırma Kontrol Devresi Açık',
  P0448: 'Buhar Emisyon Kontrol Sistemi Havalandırma Kontrol Devresi Kısa Devre',
  P0449: 'Buhar Emisyon Kontrol Sistemi Havalandırma Valfi/Solenoid Devresi',
  P0450: 'Buhar Emisyon Sistemi Basınç Sensörü Arızası',
  P0457: 'Buhar Emisyon Sistemi Sızıntı Tespiti (Yakıt Kapağı Gevşek/Eksik)',
  P0508: 'Rölanti Hava Kontrol Sistemi Devresi Düşük',
  P0509: 'Rölanti Hava Kontrol Sistemi Devresi Yüksek',
  P0511: 'Rölanti Hava Kontrol Devresi',
  P0524: 'Motor Yağ Basıncı Çok Düşük',
  P0532: 'A/C Soğutucu Basınç Sensörü Devresi Düşük',
  P0533: 'A/C Soğutucu Basınç Sensörü Devresi Yüksek',
  P0572: 'Fren Anahtarı A Devresi Düşük',
  P0573: 'Fren Anahtarı A Devresi Yüksek',
  P0608: 'Kontrol Modülü VSS Çıkışı "A" Arızası',
  P0609: 'Kontrol Modülü VSS Çıkışı "B" Arızası',
  P0630: 'VIN Programlanmamış veya Uyumsuz - ECM/PCM',
  P0634: 'PCM/ECM/TCM Dahili Sıcaklığı Çok Yüksek',
  P0638: 'Gaz Kelebeği Aktüatörü Kontrol Aralığı/Performansı (Banka 1)',
  P0639: 'Gaz Kelebeği Aktüatörü Kontrol Aralığı/Performansı (Banka 2)',
  P0709: 'Vites Aralık Sensörü Devresi Kesintili',
  P0726: 'Motor Devri Giriş Devresi Aralığı/Performansı',
  P0727: 'Motor Devri Giriş Devresi Sinyali Yok',
  P0728: 'Motor Devri Giriş Devresi Kesintili',
  P0840: 'Şanzıman Akışkan Basınç Sensörü/Anahtarı A Devresi',
  P0841: 'Şanzıman Akışkan Basınç Sensörü/Anahtarı A Aralık/Performans',
  P0842: 'Şanzıman Akışkan Basınç Sensörü/Anahtarı A Düşük',
  P0843: 'Şanzıman Akışkan Basınç Sensörü/Anahtarı A Yüksek',
  P0844: 'Şanzıman Akışkan Basınç Sensörü/Anahtarı A Kesintili',
  P0845: 'Şanzıman Akışkan Basınç Sensörü/Anahtarı B Devresi',
  P0900: 'Debriyaj Aktüatörü Devresi / Açık',
  P0901: 'Debriyaj Aktüatörü Devresi Aralık/Performans',
  P0902: 'Debriyaj Aktüatörü Devresi Düşük',
  P0903: 'Debriyaj Aktüatörü Devresi Yüksek',
  P0960: 'Basınç Kontrol Solenoid A Kontrol Devresi Açık',
  P0961: 'Basınç Kontrol Solenoid A Kontrol Devresi Aralık/Performans',
  P0962: 'Basınç Kontrol Solenoid A Kontrol Devresi Düşük',
  P0963: 'Basınç Kontrol Solenoid A Kontrol Devresi Yüksek',
  B0001: 'Sürücü Ön Kademe 1 Açılma Kontrolü Arızası',
  B0002: 'Sürücü Ön Kademe 2 Açılma Kontrolü Arızası',
  B0003: 'Sürücü Ön Kademe 3 Açılma Kontrolü Arızası',
  B0004: 'Sürücü Diz Açılma Kontrolü Arızası',
  B0005: 'Koltuk Sınırlayıcı Açılma Kontrolü Arızası',
  B0014: 'Sürücü Yan Hava Yastığı Açılma Kontrolü Devresi',
  B0015: 'Yolcu Yan Hava Yastığı Açılma Kontrolü Devresi',
  C0034: 'Sağ Ön Teker Hız Sensörü',
  C003A: 'Sağ Arka Teker Hız Sensörü',
  C0043: 'Fren Hidrolik Basıncı C',
  C0044: 'Fren Hidrolik Basıncı D',
  C0047: 'ABS Pompa Rölesi Devresi',
  C0048: 'ABS Pompa Motor Sensörü Devresi',
  C0052: 'Direksiyon Açı Sensörü Devresi',
  C0061: 'Yanal İvme Sensörü Devresi',
  C0062: 'Uzunlamasına İvme Sensörü Devresi',
  C0063: 'Yaw Rate Sensörü Devresi',
  C0064: 'Roll Rate Sensörü Devresi',
  C0081: 'Fren Anahtarı C Devresi',
  U0004: 'Yüksek Hızlı CAN İletişim Bus + Açık',
  U0005: 'Yüksek Hızlı CAN İletişim Bus + Yüksek',
  U0006: 'Yüksek Hızlı CAN İletişim Bus + Düşük',
  U0007: 'Yüksek Hızlı CAN İletişim Bus - Kapalı',
  U0008: 'Yüksek Hızlı CAN İletişim Bus - Açık',
  U0009: 'Yüksek Hızlı CAN İletişim Bus - Yüksek',
  U0011: 'Orta Hız CAN İletişim Bus Performans',
  U0012: 'Orta Hız CAN İletişim Bus + Kapalı',
  U0021: 'Düşük Hız CAN İletişim Bus Performans',
  U0022: 'Düşük Hız CAN İletişim Bus + Kapalı',
`;

content = content.replace(
  /};\s*export function getDTCCategory/,
  newDTCs + '\n};\n\nexport function getDTCCategory',
);
fs.writeFileSync(filePath, content, 'utf8');
console.log('DTCs appended successfully.');
